In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('./train.csv',delimiter=',')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

In [4]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
x=data.iloc[:,[2,4,5,6,7,8,9,11]]
y=data.iloc[:,[1]]

In [6]:
y

     Survived
0           0
1           1
2           1
3           1
4           0
5           0
6           0
7           0
8           1
9           1
10          1
11          1
12          0
13          0
14          0
15          1
16          0
17          1
18          0
19          1
20          0
21          1
22          1
23          1
24          0
25          1
26          0
27          0
28          1
29          0
..        ...
861         0
862         1
863         0
864         0
865         1
866         1
867         0
868         0
869         1
870         0
871         1
872         0
873         0
874         1
875         1
876         0
877         0
878         0
879         1
880         1
881         0
882         0
883         0
884         0
885         0
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [7]:
type(y)

pandas.core.frame.DataFrame

In [8]:
x.info()
x.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Pclass      891 non-null int64
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Ticket      891 non-null object
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

           Pclass         Age       SibSp       Parch        Fare
count  891.000000  714.000000  891.000000  891.000000  891.000000
mean     2.308642   29.699118    0.523008    0.381594   32.204208
std      0.836071   14.526497    1.102743    0.806057   49.693429
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   20.125000    0.000000    0.000000    7.910400
50%      3.000000   28.000000    0.000000    0.000000   14.454200
75%      3.000000   38.000000    1.000000    0.000000   31.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
np.where(pd.isnull(x)==1)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  61,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109,
        121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185,
        186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260,
        264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324,
        330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384,
        388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454,
        457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502,
        507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560,
        563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611,
        612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674,
        680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766,
        768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 829,
        832, 837, 839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))

In [10]:
np.where(pd.isnull(x)==1)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  61,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109,
        121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185,
        186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260,
        264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324,
        330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384,
        388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454,
        457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502,
        507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560,
        563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611,
        612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674,
        680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766,
        768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 829,
        832, 837, 839, 846, 849, 859, 863, 868, 878, 888], dtype=int64),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))

In [11]:
lossingdata=np.where(pd.isnull(x)==1)

In [12]:
type(lossingdata)

tuple

In [13]:
x

     Pclass     Sex   Age  SibSp  Parch            Ticket      Fare Embarked
0         3    male  22.0      1      0         A/5 21171    7.2500        S
1         1  female  38.0      1      0          PC 17599   71.2833        C
2         3  female  26.0      0      0  STON/O2. 3101282    7.9250        S
3         1  female  35.0      1      0            113803   53.1000        S
4         3    male  35.0      0      0            373450    8.0500        S
5         3    male   NaN      0      0            330877    8.4583        Q
6         1    male  54.0      0      0             17463   51.8625        S
7         3    male   2.0      3      1            349909   21.0750        S
8         3  female  27.0      0      2            347742   11.1333        S
9         2  female  14.0      1      0            237736   30.0708        C
10        3  female   4.0      1      1           PP 9549   16.7000        S
11        1  female  58.0      0      0            113783   26.5500        S
12        3    male  20.0      0      0         A/5. 2151    8.0500        S
13        3    male  39.0      1      5            347082   31.2750        S
14        3  female  14.0      0      0            350406    7.8542        S
15        2  female  55.0      0      0            248706   16.0000        S
16        3    male   2.0      4      1            382652   29.1250        Q
17        2    male   NaN      0      0            244373   13.0000        S
18        3  female  31.0      1      0            345763   18.0000        S
19        3  female   NaN      0      0              2649    7.2250        C
20        2    male  35.0      0      0            239865   26.0000        S
21        2    male  34.0      0      0            248698   13.0000        S
22        3  female  15.0      0      0            330923    8.0292        Q
23        1    male  28.0      0      0            113788   35.5000        S
24        3  female   8.0      3      1            349909   21.0750        S
25        3  female  38.0      1      5            347077   31.3875        S
26        3    male   NaN      0      0              2631    7.2250        C
27        1    male  19.0      3      2             19950  263.0000        S
28        3  female   NaN      0      0            330959    7.8792        Q
29        3    male   NaN      0      0            349216    7.8958        S
..      ...     ...   ...    ...    ...               ...       ...      ...
861       2    male  21.0      1      0             28134   11.5000        S
862       1  female  48.0      0      0             17466   25.9292        S
863       3  female   NaN      8      2          CA. 2343   69.5500        S
864       2    male  24.0      0      0            233866   13.0000        S
865       2  female  42.0      0      0            236852   13.0000        S
866       2  female  27.0      1      0     SC/PARIS 2149   13.8583        C
867       1    male  31.0      0      0          PC 17590   50.4958        S
868       3    male   NaN      0      0            345777    9.5000        S
869       3    male   4.0      1      1            347742   11.1333        S
870       3    male  26.0      0      0            349248    7.8958        S
871       1  female  47.0      1      1             11751   52.5542        S
872       1    male  33.0      0      0               695    5.0000        S
873       3    male  47.0      0      0            345765    9.0000        S
874       2  female  28.0      1      0         P/PP 3381   24.0000        C
875       3  female  15.0      0      0              2667    7.2250        C
876       3    male  20.0      0      0              7534    9.8458        S
877       3    male  19.0      0      0            349212    7.8958        S
878       3    male   NaN      0      0            349217    7.8958        S
879       1  female  56.0      0      1             11767   83.1583        C
880       2  female  25.0      0      1            230433   26.0000        S
881       3    male  33.0      0      0            349257    7.8958        S
882       3  female  22.0      0      0              7552   10.5167        S
883       2    male  28.0      0      0  C.A./SOTON 34068   10.5000        S
884       3    male  25.0      0      0   SOTON/OQ 392076    7.0500        S
885       3  female  39.0      0      5            382652   29.1250        Q
886       2    male  27.0      0      0            211536   13.0000        S
887       1  female  19.0      0      0            112053   30.0000        S
888       3  female   NaN      1      2        W./C. 6607   23.4500        S
889       1    male  26.0      0      0            111369   30.0000        C
890       3    male  32.0      0      0            370376    7.7500        Q

[891 rows x 8 columns]

In [14]:
aa=np.array([np.where(x.isnull()==True)[0:1]]).reshape(-1)

In [15]:
aa

array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
        48,  55,  61,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109,
       121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185,
       186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260,
       264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324,
       330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384,
       388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454,
       457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502,
       507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560,
       563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611,
       612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674,
       680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766,
       768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 829,
       832, 837, 839, 846, 849, 859, 863, 868, 878, 888], dtype=int64)

In [16]:
lossingdata=x.iloc[aa,:]

In [17]:
lossingdata

     Pclass     Sex   Age  SibSp  Parch           Ticket      Fare Embarked
5         3    male   NaN      0      0           330877    8.4583        Q
17        2    male   NaN      0      0           244373   13.0000        S
19        3  female   NaN      0      0             2649    7.2250        C
26        3    male   NaN      0      0             2631    7.2250        C
28        3  female   NaN      0      0           330959    7.8792        Q
29        3    male   NaN      0      0           349216    7.8958        S
31        1  female   NaN      1      0         PC 17569  146.5208        C
32        3  female   NaN      0      0           335677    7.7500        Q
36        3    male   NaN      0      0             2677    7.2292        C
42        3    male   NaN      0      0           349253    7.8958        C
45        3    male   NaN      0      0  S.C./A.4. 23567    8.0500        S
46        3    male   NaN      1      0           370371   15.5000        Q
47        3  female   NaN      0      0            14311    7.7500        Q
48        3    male   NaN      2      0             2662   21.6792        C
55        1    male   NaN      0      0            19947   35.5000        S
61        1  female  38.0      0      0           113572   80.0000      NaN
64        1    male   NaN      0      0         PC 17605   27.7208        C
65        3    male   NaN      1      1             2661   15.2458        C
76        3    male   NaN      0      0           349208    7.8958        S
77        3    male   NaN      0      0           374746    8.0500        S
82        3  female   NaN      0      0           330932    7.7875        Q
87        3    male   NaN      0      0  SOTON/OQ 392086    8.0500        S
95        3    male   NaN      0      0           374910    8.0500        S
101       3    male   NaN      0      0           349215    7.8958        S
107       3    male   NaN      0      0           312991    7.7750        S
109       3  female   NaN      1      0           371110   24.1500        Q
121       3    male   NaN      0      0        A4. 54510    8.0500        S
126       3    male   NaN      0      0           370372    7.7500        Q
128       3  female   NaN      1      1             2668   22.3583        C
140       3  female   NaN      0      2             2678   15.2458        C
..      ...     ...   ...    ...    ...              ...       ...      ...
727       3  female   NaN      0      0            36866    7.7375        Q
732       2    male   NaN      0      0           239855    0.0000        S
738       3    male   NaN      0      0           349201    7.8958        S
739       3    male   NaN      0      0           349218    7.8958        S
740       1    male   NaN      0      0            16988   30.0000        S
760       3    male   NaN      0      0           358585   14.5000        S
766       1    male   NaN      0      0           112379   39.6000        C
768       3    male   NaN      1      0           371110   24.1500        Q
773       3    male   NaN      0      0             2674    7.2250        C
776       3    male   NaN      0      0           383121    7.7500        Q
778       3    male   NaN      0      0            36865    7.7375        Q
783       3    male   NaN      1      2       W./C. 6607   23.4500        S
790       3    male   NaN      0      0            12460    7.7500        Q
792       3  female   NaN      8      2         CA. 2343   69.5500        S
793       1    male   NaN      0      0         PC 17600   30.6958        C
815       1    male   NaN      0      0           112058    0.0000        S
825       3    male   NaN      0      0           368323    6.9500        Q
826       3    male   NaN      0      0             1601   56.4958        S
828       3    male   NaN      0      0           367228    7.7500        Q
829       1  female  62.0      0      0           113572   80.0000      NaN
832       3    male   NaN      0      0             2671    7.2292        C
837       3    male   NaN      0      0           392092    8.0500        S
839       1    male   NaN      0      0            11774   29.7000        C
846       3    male   NaN      8      2         CA. 2343   69.5500        S
849       1  female   NaN      1      0            17453   89.1042        C
859       3    male   NaN      0      0             2629    7.2292        C
863       3  female   NaN      8      2         CA. 2343   69.5500        S
868       3    male   NaN      0      0           345777    9.5000        S
878       3    male   NaN      0      0           349217    7.8958        S
888       3  female   NaN      1      2       W./C. 6607   23.4500        S

[179 rows x 8 columns]

In [18]:
training=x.dropna(axis=0,how='any')

In [19]:
data=x.fillna(value=x.median(axis=0,skipna='True'))

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Ticket      891 non-null object
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

In [21]:
all=pd.concat([data,y],axis=1)

In [22]:
all=all.dropna(axis=0,how='any')

In [23]:
all

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,3,male,22.0,1,0,A/5 21171,7.2500,S,0
1,1,female,38.0,1,0,PC 17599,71.2833,C,1
2,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,1
3,1,female,35.0,1,0,113803,53.1000,S,1
4,3,male,35.0,0,0,373450,8.0500,S,0
5,3,male,28.0,0,0,330877,8.4583,Q,0
6,1,male,54.0,0,0,17463,51.8625,S,0
7,3,male,2.0,3,1,349909,21.0750,S,0
8,3,female,27.0,0,2,347742,11.1333,S,1
9,2,female,14.0,1,0,237736,30.0708,C,1
10,3,female,4.0,1,1,PP 9549,16.7000,S,1
11,1,female,58.0,0,0,113783,26.5500,S,1
12,3,male,20.0,0,0,A/5. 2151,8.0500,S,0
13,3,male,39.0,1,5,347082,31.2750,S,0
14,3,female,14.0,0,0,350406,7.8542,S,0
15,2,female,55.0,0,0,248706,16.0000,S,1
16,3,male,2.0,4,1,382652,29.1250,Q,0
17,2,male,28.0,0,0,244373,13.0000,S,1
18,3,female,31.0,1,0,345763,18.0000,S,0
19,3,female,28.0,0,0,2649,7.2250,C,1
20,2,male,35.0,0,0,239865,26.0000,S,0
21,2,male,34.0,0,0,248698,13.0000,S,1
22,3,female,15.0,0,0,330923,8.0292,Q,1
23,1,male,28.0,0,0,113788,35.5000,S,1
24,3,female,8.0,3,1,349909,21.0750,S,0
25,3,female,38.0,1,5,347077,31.3875,S,1
26,3,male,28.0,0,0,2631,7.2250,C,0
27,1,male,19.0,3,2,19950,263.0000,S,0
28,3,female,28.0,0,0,330959,7.8792,Q,1
29,3,male,28.0,0,0,349216,7.8958,S,0
...,...,...,...,...,...,...,...,...,...
861,2,male,21.0,1,0,28134,11.5000,S,0
862,1,female,48.0,0,0,17466,25.9292,S,1
863,3,female,28.0,8,2,CA. 2343,69.5500,S,0
864,2,male,24.0,0,0,233866,13.0000,S,0
865,2,female,42.0,0,0,236852,13.0000,S,1
866,2,female,27.0,1,0,SC/PARIS 2149,13.8583,C,1
867,1,male,31.0,0,0,PC 17590,50.4958,S,0
868,3,male,28.0,0,0,345777,9.5000,S,0
869,3,male,4.0,1,1,347742,11.1333,S,1
870,3,male,26.0,0,0,349248,7.8958,S,0
871,1,female,47.0,1,1,11751,52.5542,S,1
872,1,male,33.0,0,0,695,5.0000,S,0
873,3,male,47.0,0,0,345765,9.0000,S,0
874,2,female,28.0,1,0,P/PP 3381,24.0000,C,1
875,3,female,15.0,0,0,2667,7.2250,C,1
876,3,male,20.0,0,0,7534,9.8458,S,0
877,3,male,19.0,0,0,349212,7.8958,S,0
878,3,male,28.0,0,0,349217,7.8958,S,0
879,1,female,56.0,0,1,11767,83.1583,C,1
880,2,female,25.0,0,1,230433,26.0000,S,1
881,3,male,33.0,0,0,349257,7.8958,S,0
882,3,female,22.0,0,0,7552,10.5167,S,0
883,2,male,28.0,0,0,C.A./SOTON 34068,10.5000,S,0
884,3,male,25.0,0,0,SOTON/OQ 392076,7.0500,S,0
885,3,female,39.0,0,5,382652,29.1250,Q,0
886,2,male,27.0,0,0,211536,13.0000,S,0
887,1,female,19.0,0,0,112053,30.0000,S,1
888,3,female,28.0,1,2,W./C. 6607,23.4500,S,0
889,1,male,26.0,0,0,111369,30.0000,C,1
890,3,male,32.0,0,0,370376,7.7500,Q,0

In [24]:
y=all.iloc[:,[-1]]

In [25]:
x=all.iloc[:,0:-1]

In [26]:
x=x.iloc[:,[0,1,2,3,4,6,7]]

In [27]:
x

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  22.0      1      0    7.2500        S
1         1  female  38.0      1      0   71.2833        C
2         3  female  26.0      0      0    7.9250        S
3         1  female  35.0      1      0   53.1000        S
4         3    male  35.0      0      0    8.0500        S
5         3    male  28.0      0      0    8.4583        Q
6         1    male  54.0      0      0   51.8625        S
7         3    male   2.0      3      1   21.0750        S
8         3  female  27.0      0      2   11.1333        S
9         2  female  14.0      1      0   30.0708        C
10        3  female   4.0      1      1   16.7000        S
11        1  female  58.0      0      0   26.5500        S
12        3    male  20.0      0      0    8.0500        S
13        3    male  39.0      1      5   31.2750        S
14        3  female  14.0      0      0    7.8542        S
15        2  female  55.0      0      0   16.0000        S
16        3    male   2.0      4      1   29.1250        Q
17        2    male  28.0      0      0   13.0000        S
18        3  female  31.0      1      0   18.0000        S
19        3  female  28.0      0      0    7.2250        C
20        2    male  35.0      0      0   26.0000        S
21        2    male  34.0      0      0   13.0000        S
22        3  female  15.0      0      0    8.0292        Q
23        1    male  28.0      0      0   35.5000        S
24        3  female   8.0      3      1   21.0750        S
25        3  female  38.0      1      5   31.3875        S
26        3    male  28.0      0      0    7.2250        C
27        1    male  19.0      3      2  263.0000        S
28        3  female  28.0      0      0    7.8792        Q
29        3    male  28.0      0      0    7.8958        S
..      ...     ...   ...    ...    ...       ...      ...
861       2    male  21.0      1      0   11.5000        S
862       1  female  48.0      0      0   25.9292        S
863       3  female  28.0      8      2   69.5500        S
864       2    male  24.0      0      0   13.0000        S
865       2  female  42.0      0      0   13.0000        S
866       2  female  27.0      1      0   13.8583        C
867       1    male  31.0      0      0   50.4958        S
868       3    male  28.0      0      0    9.5000        S
869       3    male   4.0      1      1   11.1333        S
870       3    male  26.0      0      0    7.8958        S
871       1  female  47.0      1      1   52.5542        S
872       1    male  33.0      0      0    5.0000        S
873       3    male  47.0      0      0    9.0000        S
874       2  female  28.0      1      0   24.0000        C
875       3  female  15.0      0      0    7.2250        C
876       3    male  20.0      0      0    9.8458        S
877       3    male  19.0      0      0    7.8958        S
878       3    male  28.0      0      0    7.8958        S
879       1  female  56.0      0      1   83.1583        C
880       2  female  25.0      0      1   26.0000        S
881       3    male  33.0      0      0    7.8958        S
882       3  female  22.0      0      0   10.5167        S
883       2    male  28.0      0      0   10.5000        S
884       3    male  25.0      0      0    7.0500        S
885       3  female  39.0      0      5   29.1250        Q
886       2    male  27.0      0      0   13.0000        S
887       1  female  19.0      0      0   30.0000        S
888       3  female  28.0      1      2   23.4500        S
889       1    male  26.0      0      0   30.0000        C
890       3    male  32.0      0      0    7.7500        Q

[889 rows x 7 columns]

In [28]:
x=pd.get_dummies(x)

In [29]:
y

     Survived
0           0
1           1
2           1
3           1
4           0
5           0
6           0
7           0
8           1
9           1
10          1
11          1
12          0
13          0
14          0
15          1
16          0
17          1
18          0
19          1
20          0
21          1
22          1
23          1
24          0
25          1
26          0
27          0
28          1
29          0
..        ...
861         0
862         1
863         0
864         0
865         1
866         1
867         0
868         0
869         1
870         0
871         1
872         0
873         0
874         1
875         1
876         0
877         0
878         0
879         1
880         1
881         0
882         0
883         0
884         0
885         0
886         0
887         1
888         0
889         1
890         0

[889 rows x 1 columns]

In [30]:
all=pd.concat([x,y],axis=1)

In [31]:
all

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Survived
0,3,22.0,1,0,7.2500,0,1,0,0,1,0
1,1,38.0,1,0,71.2833,1,0,1,0,0,1
2,3,26.0,0,0,7.9250,1,0,0,0,1,1
3,1,35.0,1,0,53.1000,1,0,0,0,1,1
4,3,35.0,0,0,8.0500,0,1,0,0,1,0
5,3,28.0,0,0,8.4583,0,1,0,1,0,0
6,1,54.0,0,0,51.8625,0,1,0,0,1,0
7,3,2.0,3,1,21.0750,0,1,0,0,1,0
8,3,27.0,0,2,11.1333,1,0,0,0,1,1
9,2,14.0,1,0,30.0708,1,0,1,0,0,1
10,3,4.0,1,1,16.7000,1,0,0,0,1,1
11,1,58.0,0,0,26.5500,1,0,0,0,1,1
12,3,20.0,0,0,8.0500,0,1,0,0,1,0
13,3,39.0,1,5,31.2750,0,1,0,0,1,0
14,3,14.0,0,0,7.8542,1,0,0,0,1,0
15,2,55.0,0,0,16.0000,1,0,0,0,1,1
16,3,2.0,4,1,29.1250,0,1,0,1,0,0
17,2,28.0,0,0,13.0000,0,1,0,0,1,1
18,3,31.0,1,0,18.0000,1,0,0,0,1,0
19,3,28.0,0,0,7.2250,1,0,1,0,0,1
20,2,35.0,0,0,26.0000,0,1,0,0,1,0
21,2,34.0,0,0,13.0000,0,1,0,0,1,1
22,3,15.0,0,0,8.0292,1,0,0,1,0,1
23,1,28.0,0,0,35.5000,0,1,0,0,1,1
24,3,8.0,3,1,21.0750,1,0,0,0,1,0
25,3,38.0,1,5,31.3875,1,0,0,0,1,1
26,3,28.0,0,0,7.2250,0,1,1,0,0,0
27,1,19.0,3,2,263.0000,0,1,0,0,1,0
28,3,28.0,0,0,7.8792,1,0,0,1,0,1
29,3,28.0,0,0,7.8958,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
861,2,21.0,1,0,11.5000,0,1,0,0,1,0
862,1,48.0,0,0,25.9292,1,0,0,0,1,1
863,3,28.0,8,2,69.5500,1,0,0,0,1,0
864,2,24.0,0,0,13.0000,0,1,0,0,1,0
865,2,42.0,0,0,13.0000,1,0,0,0,1,1
866,2,27.0,1,0,13.8583,1,0,1,0,0,1
867,1,31.0,0,0,50.4958,0,1,0,0,1,0
868,3,28.0,0,0,9.5000,0,1,0,0,1,0
869,3,4.0,1,1,11.1333,0,1,0,0,1,1
870,3,26.0,0,0,7.8958,0,1,0,0,1,0
871,1,47.0,1,1,52.5542,1,0,0,0,1,1
872,1,33.0,0,0,5.0000,0,1,0,0,1,0
873,3,47.0,0,0,9.0000,0,1,0,0,1,0
874,2,28.0,1,0,24.0000,1,0,1,0,0,1
875,3,15.0,0,0,7.2250,1,0,1,0,0,1
876,3,20.0,0,0,9.8458,0,1,0,0,1,0
877,3,19.0,0,0,7.8958,0,1,0,0,1,0
878,3,28.0,0,0,7.8958,0,1,0,0,1,0
879,1,56.0,0,1,83.1583,1,0,1,0,0,1
880,2,25.0,0,1,26.0000,1,0,0,0,1,1
881,3,33.0,0,0,7.8958,0,1,0,0,1,0
882,3,22.0,0,0,10.5167,1,0,0,0,1,0
883,2,28.0,0,0,10.5000,0,1,0,0,1,0
884,3,25.0,0,0,7.0500,0,1,0,0,1,0
885,3,39.0,0,5,29.1250,1,0,0,1,0,0
886,2,27.0,0,0,13.0000,0,1,0,0,1,0
887,1,19.0,0,0,30.0000,1,0,0,0,1,1
888,3,28.0,1,2,23.4500,1,0,0,0,1,0
889,1,26.0,0,0,30.0000,0,1,1,0,0,1
890,3,32.0,0,0,7.7500,0,1,0,1,0,0

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y)

In [33]:
X_train

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
859,3,28.0,0,0,7.2292,0,1,1,0,0
743,3,24.0,1,0,16.1000,0,1,0,0,1
227,3,20.5,0,0,7.2500,0,1,0,0,1
207,3,26.0,0,0,18.7875,0,1,1,0,0
144,2,18.0,0,0,11.5000,0,1,0,0,1
847,3,35.0,0,0,7.8958,0,1,1,0,0
704,3,26.0,1,0,7.8542,0,1,0,0,1
332,1,38.0,0,1,153.4625,0,1,0,0,1
423,3,28.0,1,1,14.4000,1,0,0,0,1
31,1,28.0,1,0,146.5208,1,0,1,0,0
167,3,45.0,1,4,27.9000,1,0,0,0,1
817,2,31.0,1,1,37.0042,0,1,1,0,0
301,3,28.0,2,0,23.2500,0,1,0,1,0
735,3,28.5,0,0,16.1000,0,1,0,0,1
377,1,27.0,0,2,211.5000,0,1,1,0,0
237,2,8.0,0,2,26.2500,1,0,0,0,1
350,3,23.0,0,0,9.2250,0,1,0,0,1
288,2,42.0,0,0,13.0000,0,1,0,0,1
599,1,49.0,1,0,56.9292,0,1,1,0,0
141,3,22.0,0,0,7.7500,1,0,0,0,1
187,1,45.0,0,0,26.5500,0,1,0,0,1
848,2,28.0,0,1,33.0000,0,1,0,0,1
823,3,27.0,0,1,12.4750,1,0,0,0,1
435,1,14.0,1,2,120.0000,1,0,0,0,1
857,1,51.0,0,0,26.5500,0,1,0,0,1
386,3,1.0,5,2,46.9000,0,1,0,0,1
385,2,18.0,0,0,73.5000,0,1,0,0,1
764,3,16.0,0,0,7.7750,0,1,0,0,1
573,3,28.0,0,0,7.7500,1,0,0,1,0
273,1,37.0,0,1,29.7000,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
864,2,24.0,0,0,13.0000,0,1,0,0,1
186,3,28.0,1,0,15.5000,1,0,0,1,0
652,3,21.0,0,0,8.4333,0,1,0,0,1
856,1,45.0,1,1,164.8667,1,0,0,0,1
498,1,25.0,1,2,151.5500,1,0,0,0,1
500,3,17.0,0,0,8.6625,0,1,0,0,1
99,2,34.0,1,0,26.0000,0,1,0,0,1
442,3,25.0,1,0,7.7750,0,1,0,0,1
91,3,20.0,0,0,7.8542,0,1,0,0,1
112,3,22.0,0,0,8.0500,0,1,0,0,1
630,1,80.0,0,0,30.0000,0,1,0,0,1
36,3,28.0,0,0,7.2292,0,1,1,0,0
543,2,32.0,1,0,26.0000,0,1,0,0,1
731,3,11.0,0,0,18.7875,0,1,1,0,0
419,3,10.0,0,2,24.1500,1,0,0,0,1
346,2,40.0,0,0,13.0000,1,0,0,0,1
284,1,28.0,0,0,26.0000,0,1,0,0,1
721,3,17.0,1,0,7.0542,0,1,0,0,1
582,2,54.0,0,0,26.0000,0,1,0,0,1
622,3,20.0,1,1,15.7417,0,1,1,0,0
623,3,21.0,0,0,7.8542,0,1,0,0,1
106,3,21.0,0,0,7.6500,1,0,0,0,1
659,1,58.0,0,2,113.2750,0,1,1,0,0
782,1,29.0,0,0,30.0000,0,1,0,0,1
658,2,23.0,0,0,13.0000,0,1,0,0,1
827,2,1.0,0,2,37.0042,0,1,1,0,0
509,3,26.0,0,0,56.4958,0,1,0,0,1
664,3,20.0,1,0,7.9250,0,1,0,0,1
402,3,21.0,1,0,9.8250,1,0,0,0,1
725,3,20.0,0,0,8.6625,0,1,0,0,1

In [34]:
import torch
from torch.utils import data
from torch.autograd import Variable

# Dataframe 转为Tensor：先values.reshape变为ndarray，在用Variable 控制

In [1]:
batch_size=20
train=pd.concat([X_train,y_train],axis=1)
train=train.values.reshape(np.size(train,0),-1)
train=Variable(torch.Tensor([train]))


test=pd.concat([X_test,y_test],axis=1)
test=test.values.reshape(np.size(test,0),-1)
test=Variable(torch.Tensor([test]))

NameError: name 'pd' is not defined

In [36]:
np.shape(train)

torch.Size([1, 666, 11])

train_loader=torch.utils.data.DataLoader(dataset=train,
                                         batch_size=batch_size,
                                         shuffle=True,num_workers=0)
test_loader=torch.utils.data.DataLoader(dataset=test,
                                        batch_size=batch_size,
                                        shuffle=False,num_workers=0)

In [38]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.l1=torch.nn.Linear(10,6)
        self.l2=torch.nn.Linear(6,4)
        self.l3=torch.nn.Linear(4,1)
        self.sigmoid=torch.nn.Sigmoid()
        
        
    def forward(self,x):
        out1=self.sigmoid(self.l1(x))
        out2=self.sigmoid(self.l2(out1))
        y_pred=self.sigmoid(self.l3(out2))
        
        
        return y_pred

In [39]:
model=Model()
criterion=torch.nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)

In [52]:
for epoch in range(4000):
    inputs,labels=train[0,:,[0,1,2,3,4,5,6,7,8,9]],train[0,:,[-1]]
    y_pred=model(inputs)
    loss=criterion(y_pred,labels)
    print(epoch,i,loss.data[0])
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number

0 0 tensor(0.6496)
1 0 tensor(0.6495)
2 0 tensor(0.6495)
3 0 tensor(0.6494)
4 0 tensor(0.6494)
5 0 tensor(0.6493)
6 0 tensor(0.6492)
7 0 tensor(0.6492)
8 0 tensor(0.6491)
9 0 tensor(0.6490)
10 0 tensor(0.6490)
11 0 tensor(0.6489)
12 0 tensor(0.6488)
13 0 tensor(0.6488)
14 0 tensor(0.6487)
15 0 tensor(0.6487)
16 0 tensor(0.6486)
17 0 tensor(0.6485)
18 0 tensor(0.6485)
19 0 tensor(0.6484)
20 0 tensor(0.6483)
21 0 tensor(0.6483)
22 0 tensor(0.6482)
23 0 tensor(0.6481)
24 0 tensor(0.6481)
25 0 tensor(0.6480)
26 0 tensor(0.6479)
27 0 tensor(0.6479)
28 0 tensor(0.6478)
29 0 tensor(0.6477)
30 0 tensor(0.6477)
31 0 tensor(0.6476)
32 0 tensor(0.6475)
33 0 tensor(0.6475)
34 0 tensor(0.6474)
35 0 tensor(0.6473)
36 0 tensor(0.6473)
37 0 tensor(0.6472)
38 0 tensor(0.6471)
39 0 tensor(0.6471)
40 0 tensor(0.6470)
41 0 tensor(0.6469)
42 0 tensor(0.6469)
43 0 tensor(0.6468)
44 0 tensor(0.6467)
45 0 tensor(0.6466)
46 0 tensor(0.6466)
47 0 tensor(0.6465)
48 0 tensor(0.6464)
49 0 tensor(0.6464)
50 0 tensor(0.6463)
51 0 tensor(0.6462)
52 0 tensor(0.6462)
53 0 tensor(0.6461)
54 0 tensor(0.6460)
55 0 tensor(0.6459)
56 0 tensor(0.6459)
57 0 tensor(0.6458)
58 0 tensor(0.6457)
59 0 tensor(0.6457)
60 0 tensor(0.6456)
61 0 tensor(0.6455)
62 0 tensor(0.6455)
63 0 tensor(0.6454)
64 0 tensor(0.6453)
65 0 tensor(0.6452)
66 0 tensor(0.6452)
67 0 tensor(0.6451)
68 0 tensor(0.6450)
69 0 tensor(0.6449)
70 0 tensor(0.6449)
71 0 tensor(0.6448)
72 0 tensor(0.6447)
73 0 tensor(0.6447)
74 0 tensor(0.6446)
75 0 tensor(0.6445)
76 0 tensor(0.6444)
77 0 tensor(0.6444)
78 0 tensor(0.6443)
79 0 tensor(0.6442)
80 0 tensor(0.6441)
81 0 tensor(0.6441)
82 0 tensor(0.6440)
83 0 tensor(0.6439)
84 0 tensor(0.6438)
85 0 tensor(0.6438)
86 0 tensor(0.6437)
87 0 tensor(0.6436)
88 0 tensor(0.6435)
89 0 tensor(0.6435)
90 0 tensor(0.6434)
91 0 tensor(0.6433)
92 0 tensor(0.6432)
93 0 tensor(0.6432)
94 0 tensor(0.6431)
95 0 tensor(0.6430)
96 0 tensor(0.6429)
97 0 tensor(0.6429)
98 0 tensor(0.6428)
99 0 tensor(0.6427)
100 0 tensor(0.6426)
101 0 tensor(0.6425)
102 0 tensor(0.6425)
103 0 tensor(0.6424)
104 0 tensor(0.6423)
105 0 tensor(0.6422)
106 0 tensor(0.6422)
107 0 tensor(0.6421)
108 0 tensor(0.6420)
109 0 tensor(0.6419)
110 0 tensor(0.6418)
111 0 tensor(0.6418)
112 0 tensor(0.6417)
113 0 tensor(0.6416)
114 0 tensor(0.6415)
115 0 tensor(0.6414)
116 0 tensor(0.6414)
117 0 tensor(0.6413)
118 0 tensor(0.6412)
119 0 tensor(0.6411)
120 0 tensor(0.6410)
121 0 tensor(0.6410)
122 0 tensor(0.6409)
123 0 tensor(0.6408)
124 0 tensor(0.6407)
125 0 tensor(0.6406)
126 0 tensor(0.6405)
127 0 tensor(0.6405)
128 0 tensor(0.6404)
129 0 tensor(0.6403)
130 0 tensor(0.6402)
131 0 tensor(0.6401)
132 0 tensor(0.6400)
133 0 tensor(0.6400)
134 0 tensor(0.6399)
135 0 tensor(0.6398)
136 0 tensor(0.6397)
137 0 tensor(0.6396)
138 0 tensor(0.6395)
139 0 tensor(0.6395)
140 0 tensor(0.6394)
141 0 tensor(0.6393)
142 0 tensor(0.6392)
143 0 tensor(0.6391)
144 0 tensor(0.6390)
145 0 tensor(0.6389)
146 0 tensor(0.6389)
147 0 tensor(0.6388)
148 0 tensor(0.6387)
149 0 tensor(0.6386)
150 0 tensor(0.6385)
151 0 tensor(0.6384)
152 0 tensor(0.6384)
153 0 tensor(0.6383)
154 0 tensor(0.6382)
155 0 tensor(0.6381)
156 0 tensor(0.6380)
157 0 tensor(0.6379)
158 0 tensor(0.6378)
159 0 tensor(0.6378)
160 0 tensor(0.6377)
161 0 tensor(0.6376)
162 0 tensor(0.6375)
163 0 tensor(0.6374)
164 0 tensor(0.6373)
165 0 tensor(0.6372)
166 0 tensor(0.6372)
167 0 tensor(0.6371)
168 0 tensor(0.6370)
169 0 tensor(0.6369)
170 0 tensor(0.6368)
171 0 tensor(0.6367)
172 0 tensor(0.6366)
173 0 tensor(0.6366)
174 0 tensor(0.6365)
175 0 tensor(0.6364)
176 0 tensor(0.6363)
177 0 tensor(0.6362)
178 0 tensor(0.6361)
179 0 tensor(0.6360)
180 0 tensor(0.6359)
181 0 tensor(0.6359)
182 0 tensor(0.6358)
183 0 tensor(0.6357)
184 0 tensor(0.6356)
185 0 tensor(0.6355)
186 0 tensor(0.6354)
187 0 tensor(0.6353)
188 0 tensor(0.6353)
189 0 tensor(0.6352)
190 0 tensor(0.6351)
191 0 tensor(0.6350)
192 0 tensor(0.6349)
193 0 tensor(0.6348)
194 0 tensor(0.6347)
195 0 tensor(0.6346)
196 0 tensor(0.6346)
197 0 tensor(0.6345)
198 0 tensor(0.6344)
199 0 tensor(0.6343)
200 0 tensor(0.6342)
201 0 tensor(0.6341)
202 0 tensor(0.6340)
203 0 tensor(0.6340)
204 0 tensor(0.6339)
205 0 tensor(0.6338)
206 0 tensor(0.6337)
207 0 tensor(0.6336)
208 0 tensor(0.6335)
209 0 tensor(0.6334)
210 0 tensor(0.6333)
211 0 tensor(0.6333)
212 0 tensor(0.6332)
213 0 tensor(0.6331)
214 0 tensor(0.6330)
215 0 tensor(0.6329)
216 0 tensor(0.6328)
217 0 tensor(0.6327)
218 0 tensor(0.6326)
219 0 tensor(0.6326)
220 0 tensor(0.6325)
221 0 tensor(0.6324)
222 0 tensor(0.6323)
223 0 tensor(0.6322)
224 0 tensor(0.6321)
225 0 tensor(0.6320)
226 0 tensor(0.6319)
227 0 tensor(0.6319)
228 0 tensor(0.6318)
229 0 tensor(0.6317)
230 0 tensor(0.6316)
231 0 tensor(0.6315)
232 0 tensor(0.6314)
233 0 tensor(0.6313)
234 0 tensor(0.6312)
235 0 tensor(0.6312)
236 0 tensor(0.6311)
237 0 tensor(0.6310)
238 0 tensor(0.6309)
239 0 tensor(0.6308)
240 0 tensor(0.6307)
241 0 tensor(0.6306)
242 0 tensor(0.6305)
243 0 tensor(0.6305)
244 0 tensor(0.6304)
245 0 tensor(0.6303)
246 0 tensor(0.6302)
247 0 tensor(0.6301)
248 0 tensor(0.6300)
249 0 tensor(0.6299)
250 0 tensor(0.6298)
251 0 tensor(0.6298)
252 0 tensor(0.6297)
253 0 tensor(0.6296)
254 0 tensor(0.6295)
255 0 tensor(0.6294)
256 0 tensor(0.6293)
257 0 tensor(0.6292)
258 0 tensor(0.6291)
259 0 tensor(0.6291)
260 0 tensor(0.6290)
261 0 tensor(0.6289)
262 0 tensor(0.6288)
263 0 tensor(0.6287)
264 0 tensor(0.6286)
265 0 tensor(0.6285)
266 0 tensor(0.6284)
267 0 tensor(0.6284)
268 0 tensor(0.6283)
269 0 tensor(0.6282)
270 0 tensor(0.6281)
271 0 tensor(0.6280)
272 0 tensor(0.6279)
273 0 tensor(0.6278)
274 0 tensor(0.6278)
275 0 tensor(0.6277)
276 0 tensor(0.6276)
277 0 tensor(0.6275)
278 0 tensor(0.6274)
279 0 tensor(0.6273)
280 0 tensor(0.6272)
281 0 tensor(0.6271)
282 0 tensor(0.6271)
283 0 tensor(0.6270)
284 0 tensor(0.6269)
285 0 tensor(0.6268)
286 0 tensor(0.6267)
287 0 tensor(0.6266)
288 0 tensor(0.6265)
289 0 tensor(0.6265)
290 0 tensor(0.6264)
291 0 tensor(0.6263)
292 0 tensor(0.6262)
293 0 tensor(0.6261)
294 0 tensor(0.6260)
295 0 tensor(0.6259)
296 0 tensor(0.6259)
297 0 tensor(0.6258)
298 0 tensor(0.6257)
299 0 tensor(0.6256)
300 0 tensor(0.6255)
301 0 tensor(0.6254)
302 0 tensor(0.6253)
303 0 tensor(0.6253)
304 0 tensor(0.6252)
305 0 tensor(0.6251)
306 0 tensor(0.6250)
307 0 tensor(0.6249)
308 0 tensor(0.6248)
309 0 tensor(0.6248)
310 0 tensor(0.6247)
311 0 tensor(0.6246)
312 0 tensor(0.6245)
313 0 tensor(0.6244)
314 0 tensor(0.6243)
315 0 tensor(0.6243)
316 0 tensor(0.6242)
317 0 tensor(0.6241)
318 0 tensor(0.6240)
319 0 tensor(0.6239)
320 0 tensor(0.6238)
321 0 tensor(0.6238)
322 0 tensor(0.6237)
323 0 tensor(0.6236)
324 0 tensor(0.6235)
325 0 tensor(0.6234)
326 0 tensor(0.6233)
327 0 tensor(0.6233)
328 0 tensor(0.6232)
329 0 tensor(0.6231)
330 0 tensor(0.6230)
331 0 tensor(0.6229)
332 0 tensor(0.6228)
333 0 tensor(0.6228)
334 0 tensor(0.6227)
335 0 tensor(0.6226)
336 0 tensor(0.6225)
337 0 tensor(0.6224)
338 0 tensor(0.6223)
339 0 tensor(0.6223)
340 0 tensor(0.6222)
341 0 tensor(0.6221)
342 0 tensor(0.6220)
343 0 tensor(0.6219)
344 0 tensor(0.6219)
345 0 tensor(0.6218)
346 0 tensor(0.6217)
347 0 tensor(0.6216)
348 0 tensor(0.6215)
349 0 tensor(0.6215)
350 0 tensor(0.6214)
351 0 tensor(0.6213)
352 0 tensor(0.6212)
353 0 tensor(0.6211)
354 0 tensor(0.6211)
355 0 tensor(0.6210)
356 0 tensor(0.6209)
357 0 tensor(0.6208)
358 0 tensor(0.6207)
359 0 tensor(0.6207)
360 0 tensor(0.6206)
361 0 tensor(0.6205)
362 0 tensor(0.6204)
363 0 tensor(0.6203)
364 0 tensor(0.6203)
365 0 tensor(0.6202)
366 0 tensor(0.6201)
367 0 tensor(0.6200)
368 0 tensor(0.6199)
369 0 tensor(0.6199)
370 0 tensor(0.6198)
371 0 tensor(0.6197)
372 0 tensor(0.6196)
373 0 tensor(0.6196)
374 0 tensor(0.6195)
375 0 tensor(0.6194)
376 0 tensor(0.6193)
377 0 tensor(0.6192)
378 0 tensor(0.6192)
379 0 tensor(0.6191)
380 0 tensor(0.6190)
381 0 tensor(0.6189)
382 0 tensor(0.6189)
383 0 tensor(0.6188)
384 0 tensor(0.6187)
385 0 tensor(0.6186)
386 0 tensor(0.6186)
387 0 tensor(0.6185)
388 0 tensor(0.6184)
389 0 tensor(0.6183)
390 0 tensor(0.6183)
391 0 tensor(0.6182)
392 0 tensor(0.6181)
393 0 tensor(0.6180)
394 0 tensor(0.6180)
395 0 tensor(0.6179)
396 0 tensor(0.6178)
397 0 tensor(0.6177)
398 0 tensor(0.6177)
399 0 tensor(0.6176)
400 0 tensor(0.6175)
401 0 tensor(0.6174)
402 0 tensor(0.6174)
403 0 tensor(0.6173)
404 0 tensor(0.6172)
405 0 tensor(0.6171)
406 0 tensor(0.6171)
407 0 tensor(0.6170)
408 0 tensor(0.6169)
409 0 tensor(0.6168)
410 0 tensor(0.6168)
411 0 tensor(0.6167)
412 0 tensor(0.6166)
413 0 tensor(0.6166)
414 0 tensor(0.6165)

415 0 tensor(0.6164)
416 0 tensor(0.6163)
417 0 tensor(0.6163)
418 0 tensor(0.6162)
419 0 tensor(0.6161)
420 0 tensor(0.6161)
421 0 tensor(0.6160)
422 0 tensor(0.6159)
423 0 tensor(0.6158)
424 0 tensor(0.6158)
425 0 tensor(0.6157)
426 0 tensor(0.6156)
427 0 tensor(0.6156)
428 0 tensor(0.6155)
429 0 tensor(0.6154)
430 0 tensor(0.6153)
431 0 tensor(0.6153)
432 0 tensor(0.6152)
433 0 tensor(0.6151)
434 0 tensor(0.6151)
435 0 tensor(0.6150)
436 0 tensor(0.6149)
437 0 tensor(0.6149)
438 0 tensor(0.6148)
439 0 tensor(0.6147)
440 0 tensor(0.6147)
441 0 tensor(0.6146)
442 0 tensor(0.6145)
443 0 tensor(0.6144)
444 0 tensor(0.6144)
445 0 tensor(0.6143)
446 0 tensor(0.6142)
447 0 tensor(0.6142)
448 0 tensor(0.6141)
449 0 tensor(0.6140)
450 0 tensor(0.6140)
451 0 tensor(0.6139)
452 0 tensor(0.6138)
453 0 tensor(0.6138)
454 0 tensor(0.6137)
455 0 tensor(0.6136)
456 0 tensor(0.6136)
457 0 tensor(0.6135)
458 0 tensor(0.6134)
459 0 tensor(0.6134)
460 0 tensor(0.6133)
461 0 tensor(0.6132)
462 0 tensor(0.6132)
463 0 tensor(0.6131)
464 0 tensor(0.6130)
465 0 tensor(0.6130)
466 0 tensor(0.6129)
467 0 tensor(0.6128)
468 0 tensor(0.6128)
469 0 tensor(0.6127)
470 0 tensor(0.6127)
471 0 tensor(0.6126)
472 0 tensor(0.6125)
473 0 tensor(0.6125)
474 0 tensor(0.6124)
475 0 tensor(0.6123)
476 0 tensor(0.6123)
477 0 tensor(0.6122)
478 0 tensor(0.6121)
479 0 tensor(0.6121)
480 0 tensor(0.6120)
481 0 tensor(0.6120)
482 0 tensor(0.6119)
483 0 tensor(0.6118)
484 0 tensor(0.6118)
485 0 tensor(0.6117)
486 0 tensor(0.6116)
487 0 tensor(0.6116)
488 0 tensor(0.6115)
489 0 tensor(0.6115)
490 0 tensor(0.6114)
491 0 tensor(0.6113)
492 0 tensor(0.6113)
493 0 tensor(0.6112)
494 0 tensor(0.6112)
495 0 tensor(0.6111)
496 0 tensor(0.6110)
497 0 tensor(0.6110)
498 0 tensor(0.6109)
499 0 tensor(0.6108)
500 0 tensor(0.6108)
501 0 tensor(0.6107)
502 0 tensor(0.6107)
503 0 tensor(0.6106)
504 0 tensor(0.6105)
505 0 tensor(0.6105)
506 0 tensor(0.6104)
507 0 tensor(0.6104)
508 0 tensor(0.6103)
509 0 tensor(0.6102)
510 0 tensor(0.6102)
511 0 tensor(0.6101)
512 0 tensor(0.6101)
513 0 tensor(0.6100)
514 0 tensor(0.6100)
515 0 tensor(0.6099)
516 0 tensor(0.6098)
517 0 tensor(0.6098)
518 0 tensor(0.6097)
519 0 tensor(0.6097)
520 0 tensor(0.6096)
521 0 tensor(0.6095)
522 0 tensor(0.6095)
523 0 tensor(0.6094)
524 0 tensor(0.6094)
525 0 tensor(0.6093)
526 0 tensor(0.6093)
527 0 tensor(0.6092)
528 0 tensor(0.6091)
529 0 tensor(0.6091)
530 0 tensor(0.6090)
531 0 tensor(0.6090)
532 0 tensor(0.6089)
533 0 tensor(0.6089)
534 0 tensor(0.6088)
535 0 tensor(0.6087)
536 0 tensor(0.6087)
537 0 tensor(0.6086)
538 0 tensor(0.6086)
539 0 tensor(0.6085)
540 0 tensor(0.6085)
541 0 tensor(0.6084)
542 0 tensor(0.6083)
543 0 tensor(0.6083)
544 0 tensor(0.6082)
545 0 tensor(0.6082)
546 0 tensor(0.6081)
547 0 tensor(0.6081)
548 0 tensor(0.6080)
549 0 tensor(0.6079)
550 0 tensor(0.6079)
551 0 tensor(0.6078)
552 0 tensor(0.6078)
553 0 tensor(0.6077)
554 0 tensor(0.6076)
555 0 tensor(0.6076)
556 0 tensor(0.6075)
557 0 tensor(0.6075)
558 0 tensor(0.6074)
559 0 tensor(0.6073)
560 0 tensor(0.6073)
561 0 tensor(0.6072)
562 0 tensor(0.6072)
563 0 tensor(0.6071)
564 0 tensor(0.6070)
565 0 tensor(0.6070)
566 0 tensor(0.6069)
567 0 tensor(0.6068)
568 0 tensor(0.6068)
569 0 tensor(0.6067)
570 0 tensor(0.6066)
571 0 tensor(0.6065)
572 0 tensor(0.6065)
573 0 tensor(0.6064)
574 0 tensor(0.6063)
575 0 tensor(0.6063)
576 0 tensor(0.6062)
577 0 tensor(0.6061)
578 0 tensor(0.6060)
579 0 tensor(0.6060)
580 0 tensor(0.6059)
581 0 tensor(0.6058)
582 0 tensor(0.6058)
583 0 tensor(0.6057)
584 0 tensor(0.6056)
585 0 tensor(0.6056)
586 0 tensor(0.6055)
587 0 tensor(0.6054)
588 0 tensor(0.6054)
589 0 tensor(0.6053)
590 0 tensor(0.6052)
591 0 tensor(0.6052)
592 0 tensor(0.6051)
593 0 tensor(0.6050)
594 0 tensor(0.6050)
595 0 tensor(0.6049)
596 0 tensor(0.6049)
597 0 tensor(0.6048)
598 0 tensor(0.6047)
599 0 tensor(0.6047)
600 0 tensor(0.6046)
601 0 tensor(0.6046)
602 0 tensor(0.6045)
603 0 tensor(0.6045)
604 0 tensor(0.6044)
605 0 tensor(0.6043)
606 0 tensor(0.6043)
607 0 tensor(0.6042)
608 0 tensor(0.6042)
609 0 tensor(0.6041)
610 0 tensor(0.6041)
611 0 tensor(0.6040)
612 0 tensor(0.6040)
613 0 tensor(0.6039)
614 0 tensor(0.6039)
615 0 tensor(0.6038)
616 0 tensor(0.6037)
617 0 tensor(0.6037)
618 0 tensor(0.6036)
619 0 tensor(0.6036)
620 0 tensor(0.6035)
621 0 tensor(0.6035)
622 0 tensor(0.6034)
623 0 tensor(0.6034)
624 0 tensor(0.6033)
625 0 tensor(0.6033)
626 0 tensor(0.6032)
627 0 tensor(0.6032)
628 0 tensor(0.6031)
629 0 tensor(0.6031)
630 0 tensor(0.6030)
631 0 tensor(0.6029)
632 0 tensor(0.6029)
633 0 tensor(0.6028)
634 0 tensor(0.6028)
635 0 tensor(0.6027)
636 0 tensor(0.6027)
637 0 tensor(0.6026)
638 0 tensor(0.6026)
639 0 tensor(0.6025)
640 0 tensor(0.6025)
641 0 tensor(0.6024)
642 0 tensor(0.6024)
643 0 tensor(0.6023)
644 0 tensor(0.6023)
645 0 tensor(0.6022)
646 0 tensor(0.6022)
647 0 tensor(0.6021)
648 0 tensor(0.6021)
649 0 tensor(0.6020)
650 0 tensor(0.6020)
651 0 tensor(0.6019)
652 0 tensor(0.6019)
653 0 tensor(0.6018)
654 0 tensor(0.6018)
655 0 tensor(0.6017)
656 0 tensor(0.6017)
657 0 tensor(0.6016)
658 0 tensor(0.6016)
659 0 tensor(0.6015)
660 0 tensor(0.6015)
661 0 tensor(0.6014)
662 0 tensor(0.6014)
663 0 tensor(0.6013)
664 0 tensor(0.6013)
665 0 tensor(0.6012)
666 0 tensor(0.6012)
667 0 tensor(0.6011)
668 0 tensor(0.6011)
669 0 tensor(0.6010)
670 0 tensor(0.6010)
671 0 tensor(0.6009)
672 0 tensor(0.6009)
673 0 tensor(0.6008)
674 0 tensor(0.6008)
675 0 tensor(0.6008)
676 0 tensor(0.6007)
677 0 tensor(0.6007)
678 0 tensor(0.6006)
679 0 tensor(0.6006)
680 0 tensor(0.6005)
681 0 tensor(0.6005)
682 0 tensor(0.6004)
683 0 tensor(0.6004)
684 0 tensor(0.6003)
685 0 tensor(0.6003)
686 0 tensor(0.6002)
687 0 tensor(0.6002)
688 0 tensor(0.6001)
689 0 tensor(0.6001)
690 0 tensor(0.6000)
691 0 tensor(0.6000)
692 0 tensor(0.5999)
693 0 tensor(0.5999)
694 0 tensor(0.5999)
695 0 tensor(0.5998)
696 0 tensor(0.5998)
697 0 tensor(0.5997)
698 0 tensor(0.5997)
699 0 tensor(0.5996)
700 0 tensor(0.5996)
701 0 tensor(0.5995)
702 0 tensor(0.5995)
703 0 tensor(0.5994)
704 0 tensor(0.5994)
705 0 tensor(0.5993)
706 0 tensor(0.5993)
707 0 tensor(0.5993)
708 0 tensor(0.5992)
709 0 tensor(0.5992)
710 0 tensor(0.5991)
711 0 tensor(0.5991)
712 0 tensor(0.5990)
713 0 tensor(0.5990)
714 0 tensor(0.5989)
715 0 tensor(0.5989)
716 0 tensor(0.5988)
717 0 tensor(0.5988)
718 0 tensor(0.5988)
719 0 tensor(0.5987)
720 0 tensor(0.5987)
721 0 tensor(0.5986)
722 0 tensor(0.5986)
723 0 tensor(0.5985)
724 0 tensor(0.5985)
725 0 tensor(0.5984)
726 0 tensor(0.5984)
727 0 tensor(0.5984)
728 0 tensor(0.5983)
729 0 tensor(0.5983)
730 0 tensor(0.5982)
731 0 tensor(0.5982)
732 0 tensor(0.5981)
733 0 tensor(0.5981)
734 0 tensor(0.5980)
735 0 tensor(0.5980)
736 0 tensor(0.5980)
737 0 tensor(0.5979)
738 0 tensor(0.5979)
739 0 tensor(0.5978)
740 0 tensor(0.5978)
741 0 tensor(0.5977)
742 0 tensor(0.5977)
743 0 tensor(0.5977)
744 0 tensor(0.5976)
745 0 tensor(0.5976)
746 0 tensor(0.5975)
747 0 tensor(0.5975)
748 0 tensor(0.5974)
749 0 tensor(0.5974)
750 0 tensor(0.5973)
751 0 tensor(0.5973)
752 0 tensor(0.5973)
753 0 tensor(0.5972)
754 0 tensor(0.5972)
755 0 tensor(0.5971)
756 0 tensor(0.5971)
757 0 tensor(0.5970)
758 0 tensor(0.5970)
759 0 tensor(0.5970)
760 0 tensor(0.5969)
761 0 tensor(0.5969)
762 0 tensor(0.5968)
763 0 tensor(0.5968)
764 0 tensor(0.5967)
765 0 tensor(0.5967)
766 0 tensor(0.5967)
767 0 tensor(0.5966)
768 0 tensor(0.5966)
769 0 tensor(0.5965)
770 0 tensor(0.5965)
771 0 tensor(0.5964)
772 0 tensor(0.5964)
773 0 tensor(0.5964)
774 0 tensor(0.5963)
775 0 tensor(0.5963)
776 0 tensor(0.5962)
777 0 tensor(0.5962)
778 0 tensor(0.5961)
779 0 tensor(0.5961)
780 0 tensor(0.5961)
781 0 tensor(0.5960)
782 0 tensor(0.5960)
783 0 tensor(0.5959)
784 0 tensor(0.5959)
785 0 tensor(0.5958)
786 0 tensor(0.5958)
787 0 tensor(0.5958)
788 0 tensor(0.5957)
789 0 tensor(0.5957)
790 0 tensor(0.5956)
791 0 tensor(0.5956)
792 0 tensor(0.5955)
793 0 tensor(0.5955)
794 0 tensor(0.5955)
795 0 tensor(0.5954)
796 0 tensor(0.5954)
797 0 tensor(0.5953)
798 0 tensor(0.5953)
799 0 tensor(0.5952)
800 0 tensor(0.5952)
801 0 tensor(0.5952)
802 0 tensor(0.5951)
803 0 tensor(0.5951)
804 0 tensor(0.5950)
805 0 tensor(0.5950)
806 0 tensor(0.5949)
807 0 tensor(0.5949)
808 0 tensor(0.5949)
809 0 tensor(0.5948)
810 0 tensor(0.5948)
811 0 tensor(0.5947)
812 0 tensor(0.5947)
813 0 tensor(0.5946)
814 0 tensor(0.5946)
815 0 tensor(0.5946)
816 0 tensor(0.5945)
817 0 tensor(0.5945)
818 0 tensor(0.5944)
819 0 tensor(0.5944)
820 0 tensor(0.5943)
821 0 tensor(0.5943)
822 0 tensor(0.5942)
823 0 tensor(0.5942)
824 0 tensor(0.5942)
825 0 tensor(0.5941)
826 0 tensor(0.5941)
827 0 tensor(0.5940)
828 0 tensor(0.5940)
829 0 tensor(0.5939)
830 0 tensor(0.5939)
831 0 tensor(0.5939)
832 0 tensor(0.5938)
833 0 tensor(0.5938)
834 0 tensor(0.5937)
835 0 tensor(0.5937)
836 0 tensor(0.5936)
837 0 tensor(0.5936)
838 0 tensor(0.5936)
839 0 tensor(0.5935)
840 0 tensor(0.5935)
841 0 tensor(0.5934)
842 0 tensor(0.5934)
843 0 tensor(0.5933)
844 0 tensor(0.5933)
845 0 tensor(0.5932)
846 0 tensor(0.5932)
847 0 tensor(0.5932)
848 0 tensor(0.5931)
849 0 tensor(0.5931)
850 0 tensor(0.5930)
851 0 tensor(0.5930)
852 0 tensor(0.5929)
853 0 tensor(0.5929)
854 0 tensor(0.5928)
855 0 tensor(0.5928)
856 0 tensor(0.5928)
857 0 tensor(0.5927)
858 0 tensor(0.5927)
859 0 tensor(0.5926)
860 0 tensor(0.5926)
861 0 tensor(0.5925)
862 0 tensor(0.5925)
863 0 tensor(0.5924)
864 0 tensor(0.5924)
865 0 tensor(0.5923)
866 0 tensor(0.5923)
867 0 tensor(0.5922)
868 0 tensor(0.5922)
869 0 tensor(0.5922)
870 0 tensor(0.5921)
871 0 tensor(0.5921)
872 0 tensor(0.5920)
873 0 tensor(0.5920)

874 0 tensor(0.5919)
875 0 tensor(0.5919)
876 0 tensor(0.5918)
877 0 tensor(0.5918)
878 0 tensor(0.5917)
879 0 tensor(0.5917)
880 0 tensor(0.5916)
881 0 tensor(0.5916)
882 0 tensor(0.5915)
883 0 tensor(0.5915)
884 0 tensor(0.5914)
885 0 tensor(0.5914)
886 0 tensor(0.5913)
887 0 tensor(0.5913)
888 0 tensor(0.5912)
889 0 tensor(0.5912)
890 0 tensor(0.5911)
891 0 tensor(0.5911)
892 0 tensor(0.5910)
893 0 tensor(0.5910)
894 0 tensor(0.5909)
895 0 tensor(0.5909)
896 0 tensor(0.5908)
897 0 tensor(0.5908)
898 0 tensor(0.5907)
899 0 tensor(0.5907)
900 0 tensor(0.5906)
901 0 tensor(0.5906)
902 0 tensor(0.5905)
903 0 tensor(0.5905)
904 0 tensor(0.5904)
905 0 tensor(0.5904)
906 0 tensor(0.5903)
907 0 tensor(0.5903)
908 0 tensor(0.5902)
909 0 tensor(0.5902)
910 0 tensor(0.5901)
911 0 tensor(0.5901)
912 0 tensor(0.5900)
913 0 tensor(0.5900)
914 0 tensor(0.5899)
915 0 tensor(0.5899)
916 0 tensor(0.5898)
917 0 tensor(0.5898)
918 0 tensor(0.5897)
919 0 tensor(0.5897)
920 0 tensor(0.5896)
921 0 tensor(0.5896)
922 0 tensor(0.5895)
923 0 tensor(0.5895)
924 0 tensor(0.5894)
925 0 tensor(0.5894)
926 0 tensor(0.5893)
927 0 tensor(0.5893)
928 0 tensor(0.5892)
929 0 tensor(0.5891)
930 0 tensor(0.5891)
931 0 tensor(0.5890)
932 0 tensor(0.5890)
933 0 tensor(0.5889)
934 0 tensor(0.5889)
935 0 tensor(0.5888)
936 0 tensor(0.5888)
937 0 tensor(0.5887)
938 0 tensor(0.5887)
939 0 tensor(0.5886)
940 0 tensor(0.5886)
941 0 tensor(0.5885)
942 0 tensor(0.5885)
943 0 tensor(0.5884)
944 0 tensor(0.5884)
945 0 tensor(0.5883)
946 0 tensor(0.5883)
947 0 tensor(0.5882)
948 0 tensor(0.5881)
949 0 tensor(0.5881)
950 0 tensor(0.5880)
951 0 tensor(0.5880)
952 0 tensor(0.5879)
953 0 tensor(0.5879)
954 0 tensor(0.5878)
955 0 tensor(0.5878)
956 0 tensor(0.5877)
957 0 tensor(0.5877)
958 0 tensor(0.5876)
959 0 tensor(0.5876)
960 0 tensor(0.5875)
961 0 tensor(0.5874)
962 0 tensor(0.5874)
963 0 tensor(0.5873)
964 0 tensor(0.5873)
965 0 tensor(0.5872)
966 0 tensor(0.5872)
967 0 tensor(0.5871)
968 0 tensor(0.5871)
969 0 tensor(0.5870)
970 0 tensor(0.5869)
971 0 tensor(0.5869)
972 0 tensor(0.5868)
973 0 tensor(0.5868)
974 0 tensor(0.5867)
975 0 tensor(0.5867)
976 0 tensor(0.5866)
977 0 tensor(0.5866)
978 0 tensor(0.5865)
979 0 tensor(0.5864)
980 0 tensor(0.5864)
981 0 tensor(0.5863)
982 0 tensor(0.5863)
983 0 tensor(0.5862)
984 0 tensor(0.5862)
985 0 tensor(0.5861)
986 0 tensor(0.5860)
987 0 tensor(0.5860)
988 0 tensor(0.5859)
989 0 tensor(0.5859)
990 0 tensor(0.5858)
991 0 tensor(0.5858)
992 0 tensor(0.5857)
993 0 tensor(0.5856)
994 0 tensor(0.5856)
995 0 tensor(0.5855)
996 0 tensor(0.5855)
997 0 tensor(0.5854)
998 0 tensor(0.5854)
999 0 tensor(0.5853)
1000 0 tensor(0.5852)
1001 0 tensor(0.5852)
1002 0 tensor(0.5851)
1003 0 tensor(0.5851)
1004 0 tensor(0.5850)
1005 0 tensor(0.5849)
1006 0 tensor(0.5849)
1007 0 tensor(0.5848)
1008 0 tensor(0.5848)
1009 0 tensor(0.5847)
1010 0 tensor(0.5846)
1011 0 tensor(0.5846)
1012 0 tensor(0.5845)
1013 0 tensor(0.5845)
1014 0 tensor(0.5844)
1015 0 tensor(0.5843)
1016 0 tensor(0.5843)
1017 0 tensor(0.5842)
1018 0 tensor(0.5842)
1019 0 tensor(0.5841)
1020 0 tensor(0.5840)
1021 0 tensor(0.5840)
1022 0 tensor(0.5839)
1023 0 tensor(0.5839)
1024 0 tensor(0.5838)
1025 0 tensor(0.5837)
1026 0 tensor(0.5837)
1027 0 tensor(0.5836)
1028 0 tensor(0.5836)
1029 0 tensor(0.5835)
1030 0 tensor(0.5834)
1031 0 tensor(0.5834)
1032 0 tensor(0.5833)
1033 0 tensor(0.5832)
1034 0 tensor(0.5832)
1035 0 tensor(0.5831)
1036 0 tensor(0.5831)
1037 0 tensor(0.5830)
1038 0 tensor(0.5829)
1039 0 tensor(0.5829)
1040 0 tensor(0.5828)
1041 0 tensor(0.5827)
1042 0 tensor(0.5827)
1043 0 tensor(0.5826)
1044 0 tensor(0.5826)
1045 0 tensor(0.5825)
1046 0 tensor(0.5824)
1047 0 tensor(0.5824)
1048 0 tensor(0.5823)
1049 0 tensor(0.5822)
1050 0 tensor(0.5822)
1051 0 tensor(0.5821)
1052 0 tensor(0.5820)
1053 0 tensor(0.5820)
1054 0 tensor(0.5819)
1055 0 tensor(0.5818)
1056 0 tensor(0.5818)
1057 0 tensor(0.5817)
1058 0 tensor(0.5816)
1059 0 tensor(0.5816)
1060 0 tensor(0.5815)
1061 0 tensor(0.5815)
1062 0 tensor(0.5814)
1063 0 tensor(0.5813)
1064 0 tensor(0.5813)
1065 0 tensor(0.5812)
1066 0 tensor(0.5811)
1067 0 tensor(0.5811)
1068 0 tensor(0.5810)
1069 0 tensor(0.5809)
1070 0 tensor(0.5809)
1071 0 tensor(0.5808)
1072 0 tensor(0.5807)
1073 0 tensor(0.5807)
1074 0 tensor(0.5806)
1075 0 tensor(0.5805)
1076 0 tensor(0.5805)
1077 0 tensor(0.5804)
1078 0 tensor(0.5803)
1079 0 tensor(0.5803)
1080 0 tensor(0.5802)
1081 0 tensor(0.5801)
1082 0 tensor(0.5800)
1083 0 tensor(0.5800)
1084 0 tensor(0.5799)
1085 0 tensor(0.5798)
1086 0 tensor(0.5798)
1087 0 tensor(0.5797)
1088 0 tensor(0.5796)
1089 0 tensor(0.5796)
1090 0 tensor(0.5795)
1091 0 tensor(0.5794)
1092 0 tensor(0.5794)
1093 0 tensor(0.5793)
1094 0 tensor(0.5792)
1095 0 tensor(0.5791)
1096 0 tensor(0.5791)
1097 0 tensor(0.5790)
1098 0 tensor(0.5789)
1099 0 tensor(0.5789)
1100 0 tensor(0.5788)
1101 0 tensor(0.5787)
1102 0 tensor(0.5787)
1103 0 tensor(0.5786)
1104 0 tensor(0.5785)
1105 0 tensor(0.5784)
1106 0 tensor(0.5784)
1107 0 tensor(0.5783)
1108 0 tensor(0.5782)
1109 0 tensor(0.5782)
1110 0 tensor(0.5781)
1111 0 tensor(0.5780)
1112 0 tensor(0.5779)
1113 0 tensor(0.5779)
1114 0 tensor(0.5778)
1115 0 tensor(0.5777)
1116 0 tensor(0.5776)
1117 0 tensor(0.5776)
1118 0 tensor(0.5775)
1119 0 tensor(0.5774)
1120 0 tensor(0.5774)
1121 0 tensor(0.5773)
1122 0 tensor(0.5772)
1123 0 tensor(0.5771)
1124 0 tensor(0.5771)
1125 0 tensor(0.5770)
1126 0 tensor(0.5769)
1127 0 tensor(0.5768)
1128 0 tensor(0.5768)
1129 0 tensor(0.5767)
1130 0 tensor(0.5766)
1131 0 tensor(0.5765)
1132 0 tensor(0.5765)
1133 0 tensor(0.5764)
1134 0 tensor(0.5763)
1135 0 tensor(0.5762)
1136 0 tensor(0.5761)
1137 0 tensor(0.5761)
1138 0 tensor(0.5760)
1139 0 tensor(0.5759)
1140 0 tensor(0.5758)
1141 0 tensor(0.5758)
1142 0 tensor(0.5757)
1143 0 tensor(0.5756)
1144 0 tensor(0.5755)
1145 0 tensor(0.5755)
1146 0 tensor(0.5754)
1147 0 tensor(0.5753)
1148 0 tensor(0.5752)
1149 0 tensor(0.5751)
1150 0 tensor(0.5751)
1151 0 tensor(0.5750)
1152 0 tensor(0.5749)
1153 0 tensor(0.5748)
1154 0 tensor(0.5747)
1155 0 tensor(0.5747)
1156 0 tensor(0.5746)
1157 0 tensor(0.5745)
1158 0 tensor(0.5744)
1159 0 tensor(0.5743)
1160 0 tensor(0.5742)
1161 0 tensor(0.5742)
1162 0 tensor(0.5741)
1163 0 tensor(0.5740)
1164 0 tensor(0.5739)
1165 0 tensor(0.5738)
1166 0 tensor(0.5738)
1167 0 tensor(0.5737)
1168 0 tensor(0.5736)
1169 0 tensor(0.5735)
1170 0 tensor(0.5734)
1171 0 tensor(0.5733)
1172 0 tensor(0.5732)
1173 0 tensor(0.5732)
1174 0 tensor(0.5731)
1175 0 tensor(0.5730)
1176 0 tensor(0.5729)
1177 0 tensor(0.5728)
1178 0 tensor(0.5727)
1179 0 tensor(0.5726)
1180 0 tensor(0.5725)
1181 0 tensor(0.5724)
1182 0 tensor(0.5724)
1183 0 tensor(0.5723)
1184 0 tensor(0.5722)
1185 0 tensor(0.5721)
1186 0 tensor(0.5720)
1187 0 tensor(0.5719)
1188 0 tensor(0.5718)
1189 0 tensor(0.5717)
1190 0 tensor(0.5716)
1191 0 tensor(0.5715)
1192 0 tensor(0.5714)
1193 0 tensor(0.5713)
1194 0 tensor(0.5712)
1195 0 tensor(0.5711)
1196 0 tensor(0.5710)
1197 0 tensor(0.5709)
1198 0 tensor(0.5708)
1199 0 tensor(0.5707)
1200 0 tensor(0.5705)
1201 0 tensor(0.5704)
1202 0 tensor(0.5703)
1203 0 tensor(0.5702)
1204 0 tensor(0.5701)
1205 0 tensor(0.5700)
1206 0 tensor(0.5698)
1207 0 tensor(0.5697)
1208 0 tensor(0.5696)
1209 0 tensor(0.5694)
1210 0 tensor(0.5693)
1211 0 tensor(0.5692)
1212 0 tensor(0.5690)
1213 0 tensor(0.5689)
1214 0 tensor(0.5687)
1215 0 tensor(0.5686)
1216 0 tensor(0.5684)
1217 0 tensor(0.5682)
1218 0 tensor(0.5681)
1219 0 tensor(0.5679)
1220 0 tensor(0.5678)
1221 0 tensor(0.5676)
1222 0 tensor(0.5675)
1223 0 tensor(0.5673)
1224 0 tensor(0.5672)
1225 0 tensor(0.5671)
1226 0 tensor(0.5669)
1227 0 tensor(0.5668)
1228 0 tensor(0.5667)
1229 0 tensor(0.5665)
1230 0 tensor(0.5664)
1231 0 tensor(0.5663)
1232 0 tensor(0.5662)
1233 0 tensor(0.5660)
1234 0 tensor(0.5659)
1235 0 tensor(0.5658)
1236 0 tensor(0.5657)
1237 0 tensor(0.5656)
1238 0 tensor(0.5655)
1239 0 tensor(0.5653)
1240 0 tensor(0.5652)
1241 0 tensor(0.5651)
1242 0 tensor(0.5650)
1243 0 tensor(0.5649)
1244 0 tensor(0.5647)
1245 0 tensor(0.5646)
1246 0 tensor(0.5645)
1247 0 tensor(0.5644)
1248 0 tensor(0.5643)
1249 0 tensor(0.5642)
1250 0 tensor(0.5640)
1251 0 tensor(0.5639)
1252 0 tensor(0.5638)
1253 0 tensor(0.5637)
1254 0 tensor(0.5636)
1255 0 tensor(0.5634)
1256 0 tensor(0.5633)
1257 0 tensor(0.5632)
1258 0 tensor(0.5631)
1259 0 tensor(0.5630)
1260 0 tensor(0.5628)
1261 0 tensor(0.5627)
1262 0 tensor(0.5626)
1263 0 tensor(0.5625)
1264 0 tensor(0.5624)
1265 0 tensor(0.5622)
1266 0 tensor(0.5621)
1267 0 tensor(0.5620)
1268 0 tensor(0.5619)
1269 0 tensor(0.5617)
1270 0 tensor(0.5616)
1271 0 tensor(0.5615)
1272 0 tensor(0.5614)
1273 0 tensor(0.5612)
1274 0 tensor(0.5611)
1275 0 tensor(0.5610)
1276 0 tensor(0.5609)
1277 0 tensor(0.5608)
1278 0 tensor(0.5608)
1279 0 tensor(0.5610)
1280 0 tensor(0.5617)
1281 0 tensor(0.5630)
1282 0 tensor(0.5663)
1283 0 tensor(0.5668)
1284 0 tensor(0.5689)
1285 0 tensor(0.5659)
1286 0 tensor(0.5651)
1287 0 tensor(0.5636)
1288 0 tensor(0.5632)
1289 0 tensor(0.5626)
1290 0 tensor(0.5628)
1291 0 tensor(0.5625)
1292 0 tensor(0.5631)
1293 0 tensor(0.5629)
1294 0 tensor(0.5637)
1295 0 tensor(0.5632)

1296 0 tensor(0.5637)
1297 0 tensor(0.5630)
1298 0 tensor(0.5634)
1299 0 tensor(0.5627)
1300 0 tensor(0.5630)
1301 0 tensor(0.5624)
1302 0 tensor(0.5628)
1303 0 tensor(0.5623)
1304 0 tensor(0.5629)
1305 0 tensor(0.5623)
1306 0 tensor(0.5629)
1307 0 tensor(0.5623)
1308 0 tensor(0.5628)
1309 0 tensor(0.5622)
1310 0 tensor(0.5626)
1311 0 tensor(0.5620)
1312 0 tensor(0.5625)
1313 0 tensor(0.5619)
1314 0 tensor(0.5624)
1315 0 tensor(0.5618)
1316 0 tensor(0.5623)
1317 0 tensor(0.5617)
1318 0 tensor(0.5623)
1319 0 tensor(0.5616)
1320 0 tensor(0.5621)
1321 0 tensor(0.5615)
1322 0 tensor(0.5620)
1323 0 tensor(0.5614)
1324 0 tensor(0.5619)
1325 0 tensor(0.5613)
1326 0 tensor(0.5619)
1327 0 tensor(0.5612)
1328 0 tensor(0.5618)
1329 0 tensor(0.5611)
1330 0 tensor(0.5617)
1331 0 tensor(0.5610)
1332 0 tensor(0.5616)
1333 0 tensor(0.5609)
1334 0 tensor(0.5615)
1335 0 tensor(0.5608)
1336 0 tensor(0.5614)
1337 0 tensor(0.5607)
1338 0 tensor(0.5613)
1339 0 tensor(0.5607)
1340 0 tensor(0.5612)
1341 0 tensor(0.5606)
1342 0 tensor(0.5611)
1343 0 tensor(0.5605)
1344 0 tensor(0.5610)
1345 0 tensor(0.5604)
1346 0 tensor(0.5610)
1347 0 tensor(0.5603)
1348 0 tensor(0.5609)
1349 0 tensor(0.5602)
1350 0 tensor(0.5608)
1351 0 tensor(0.5601)
1352 0 tensor(0.5607)
1353 0 tensor(0.5600)
1354 0 tensor(0.5606)
1355 0 tensor(0.5599)
1356 0 tensor(0.5605)
1357 0 tensor(0.5598)
1358 0 tensor(0.5604)
1359 0 tensor(0.5597)
1360 0 tensor(0.5604)
1361 0 tensor(0.5596)
1362 0 tensor(0.5603)
1363 0 tensor(0.5596)
1364 0 tensor(0.5602)
1365 0 tensor(0.5595)
1366 0 tensor(0.5601)
1367 0 tensor(0.5594)
1368 0 tensor(0.5600)
1369 0 tensor(0.5593)
1370 0 tensor(0.5599)
1371 0 tensor(0.5592)
1372 0 tensor(0.5598)
1373 0 tensor(0.5591)
1374 0 tensor(0.5598)
1375 0 tensor(0.5590)
1376 0 tensor(0.5597)
1377 0 tensor(0.5589)
1378 0 tensor(0.5596)
1379 0 tensor(0.5588)
1380 0 tensor(0.5595)
1381 0 tensor(0.5588)
1382 0 tensor(0.5594)
1383 0 tensor(0.5587)
1384 0 tensor(0.5594)
1385 0 tensor(0.5586)
1386 0 tensor(0.5593)
1387 0 tensor(0.5585)
1388 0 tensor(0.5592)
1389 0 tensor(0.5584)
1390 0 tensor(0.5591)
1391 0 tensor(0.5583)
1392 0 tensor(0.5590)
1393 0 tensor(0.5582)
1394 0 tensor(0.5589)
1395 0 tensor(0.5581)
1396 0 tensor(0.5589)
1397 0 tensor(0.5581)
1398 0 tensor(0.5588)
1399 0 tensor(0.5580)
1400 0 tensor(0.5587)
1401 0 tensor(0.5579)
1402 0 tensor(0.5586)
1403 0 tensor(0.5578)
1404 0 tensor(0.5586)
1405 0 tensor(0.5577)
1406 0 tensor(0.5585)
1407 0 tensor(0.5576)
1408 0 tensor(0.5584)
1409 0 tensor(0.5575)
1410 0 tensor(0.5583)
1411 0 tensor(0.5575)
1412 0 tensor(0.5582)
1413 0 tensor(0.5574)
1414 0 tensor(0.5582)
1415 0 tensor(0.5573)
1416 0 tensor(0.5581)
1417 0 tensor(0.5572)
1418 0 tensor(0.5580)
1419 0 tensor(0.5571)
1420 0 tensor(0.5579)
1421 0 tensor(0.5570)
1422 0 tensor(0.5579)
1423 0 tensor(0.5569)
1424 0 tensor(0.5578)
1425 0 tensor(0.5568)
1426 0 tensor(0.5577)
1427 0 tensor(0.5568)
1428 0 tensor(0.5576)
1429 0 tensor(0.5567)
1430 0 tensor(0.5576)
1431 0 tensor(0.5566)
1432 0 tensor(0.5575)
1433 0 tensor(0.5565)
1434 0 tensor(0.5574)
1435 0 tensor(0.5564)
1436 0 tensor(0.5574)
1437 0 tensor(0.5563)
1438 0 tensor(0.5573)
1439 0 tensor(0.5562)
1440 0 tensor(0.5572)
1441 0 tensor(0.5561)
1442 0 tensor(0.5571)
1443 0 tensor(0.5561)
1444 0 tensor(0.5571)
1445 0 tensor(0.5560)
1446 0 tensor(0.5570)
1447 0 tensor(0.5559)
1448 0 tensor(0.5569)
1449 0 tensor(0.5558)
1450 0 tensor(0.5569)
1451 0 tensor(0.5557)
1452 0 tensor(0.5568)
1453 0 tensor(0.5556)
1454 0 tensor(0.5567)
1455 0 tensor(0.5555)
1456 0 tensor(0.5567)
1457 0 tensor(0.5555)
1458 0 tensor(0.5566)
1459 0 tensor(0.5554)
1460 0 tensor(0.5565)
1461 0 tensor(0.5553)
1462 0 tensor(0.5565)
1463 0 tensor(0.5552)
1464 0 tensor(0.5564)
1465 0 tensor(0.5551)
1466 0 tensor(0.5563)
1467 0 tensor(0.5550)
1468 0 tensor(0.5563)
1469 0 tensor(0.5549)
1470 0 tensor(0.5562)
1471 0 tensor(0.5548)
1472 0 tensor(0.5561)
1473 0 tensor(0.5548)
1474 0 tensor(0.5561)
1475 0 tensor(0.5547)
1476 0 tensor(0.5560)
1477 0 tensor(0.5546)
1478 0 tensor(0.5560)
1479 0 tensor(0.5545)
1480 0 tensor(0.5559)
1481 0 tensor(0.5544)
1482 0 tensor(0.5558)
1483 0 tensor(0.5543)
1484 0 tensor(0.5558)
1485 0 tensor(0.5542)
1486 0 tensor(0.5557)
1487 0 tensor(0.5541)
1488 0 tensor(0.5557)
1489 0 tensor(0.5540)
1490 0 tensor(0.5556)
1491 0 tensor(0.5539)
1492 0 tensor(0.5556)
1493 0 tensor(0.5538)
1494 0 tensor(0.5555)
1495 0 tensor(0.5537)
1496 0 tensor(0.5554)
1497 0 tensor(0.5536)
1498 0 tensor(0.5554)
1499 0 tensor(0.5535)
1500 0 tensor(0.5553)
1501 0 tensor(0.5534)
1502 0 tensor(0.5553)
1503 0 tensor(0.5533)
1504 0 tensor(0.5552)
1505 0 tensor(0.5532)
1506 0 tensor(0.5552)
1507 0 tensor(0.5531)
1508 0 tensor(0.5551)
1509 0 tensor(0.5530)
1510 0 tensor(0.5550)
1511 0 tensor(0.5529)
1512 0 tensor(0.5550)
1513 0 tensor(0.5528)
1514 0 tensor(0.5549)
1515 0 tensor(0.5527)
1516 0 tensor(0.5549)
1517 0 tensor(0.5526)
1518 0 tensor(0.5548)
1519 0 tensor(0.5524)
1520 0 tensor(0.5548)
1521 0 tensor(0.5523)
1522 0 tensor(0.5547)
1523 0 tensor(0.5522)
1524 0 tensor(0.5547)
1525 0 tensor(0.5521)
1526 0 tensor(0.5546)
1527 0 tensor(0.5520)
1528 0 tensor(0.5546)
1529 0 tensor(0.5518)
1530 0 tensor(0.5545)
1531 0 tensor(0.5517)
1532 0 tensor(0.5545)
1533 0 tensor(0.5516)
1534 0 tensor(0.5544)
1535 0 tensor(0.5515)
1536 0 tensor(0.5544)
1537 0 tensor(0.5513)
1538 0 tensor(0.5543)
1539 0 tensor(0.5512)
1540 0 tensor(0.5543)
1541 0 tensor(0.5511)
1542 0 tensor(0.5542)
1543 0 tensor(0.5510)
1544 0 tensor(0.5542)
1545 0 tensor(0.5508)
1546 0 tensor(0.5541)
1547 0 tensor(0.5507)
1548 0 tensor(0.5541)
1549 0 tensor(0.5506)
1550 0 tensor(0.5540)
1551 0 tensor(0.5504)
1552 0 tensor(0.5540)
1553 0 tensor(0.5503)
1554 0 tensor(0.5540)
1555 0 tensor(0.5501)
1556 0 tensor(0.5539)
1557 0 tensor(0.5500)
1558 0 tensor(0.5539)
1559 0 tensor(0.5499)
1560 0 tensor(0.5539)
1561 0 tensor(0.5497)
1562 0 tensor(0.5538)
1563 0 tensor(0.5496)
1564 0 tensor(0.5538)
1565 0 tensor(0.5494)
1566 0 tensor(0.5538)
1567 0 tensor(0.5493)
1568 0 tensor(0.5537)
1569 0 tensor(0.5491)
1570 0 tensor(0.5537)
1571 0 tensor(0.5490)
1572 0 tensor(0.5537)
1573 0 tensor(0.5488)
1574 0 tensor(0.5536)
1575 0 tensor(0.5487)
1576 0 tensor(0.5536)
1577 0 tensor(0.5485)
1578 0 tensor(0.5536)
1579 0 tensor(0.5484)
1580 0 tensor(0.5536)
1581 0 tensor(0.5482)
1582 0 tensor(0.5535)
1583 0 tensor(0.5480)
1584 0 tensor(0.5536)
1585 0 tensor(0.5479)
1586 0 tensor(0.5535)
1587 0 tensor(0.5477)
1588 0 tensor(0.5536)
1589 0 tensor(0.5475)
1590 0 tensor(0.5532)
1591 0 tensor(0.5474)
1592 0 tensor(0.5542)
1593 0 tensor(0.5469)
1594 0 tensor(0.5519)
1595 0 tensor(0.5475)
1596 0 tensor(0.5583)
1597 0 tensor(0.5448)
1598 0 tensor(0.5461)
1599 0 tensor(0.5455)
1600 0 tensor(0.5616)
1601 0 tensor(0.5439)
1602 0 tensor(0.5409)
1603 0 tensor(0.5434)
1604 0 tensor(0.5671)
1605 0 tensor(0.5435)
1606 0 tensor(0.5348)
1607 0 tensor(0.5363)
1608 0 tensor(0.5575)
1609 0 tensor(0.5450)
1610 0 tensor(0.5490)
1611 0 tensor(0.5464)
1612 0 tensor(0.5659)
1613 0 tensor(0.5423)
1614 0 tensor(0.5342)
1615 0 tensor(0.5380)
1616 0 tensor(0.5698)
1617 0 tensor(0.5425)
1618 0 tensor(0.5328)
1619 0 tensor(0.5332)
1620 0 tensor(0.5511)
1621 0 tensor(0.5493)
1622 0 tensor(0.5765)
1623 0 tensor(0.5445)
1624 0 tensor(0.5363)
1625 0 tensor(0.5307)
1626 0 tensor(0.5282)
1627 0 tensor(0.5358)
1628 0 tensor(0.5742)
1629 0 tensor(0.5418)
1630 0 tensor(0.5318)
1631 0 tensor(0.5306)
1632 0 tensor(0.5438)
1633 0 tensor(0.5588)
1634 0 tensor(0.5754)
1635 0 tensor(0.5418)
1636 0 tensor(0.5312)
1637 0 tensor(0.5318)
1638 0 tensor(0.5576)
1639 0 tensor(0.5411)
1640 0 tensor(0.5452)
1641 0 tensor(0.5458)
1642 0 tensor(0.5766)
1643 0 tensor(0.5433)
1644 0 tensor(0.5346)
1645 0 tensor(0.5290)
1646 0 tensor(0.5277)
1647 0 tensor(0.5394)
1648 0 tensor(0.5786)
1649 0 tensor(0.5418)
1650 0 tensor(0.5321)
1651 0 tensor(0.5280)
1652 0 tensor(0.5323)
1653 0 tensor(0.5559)
1654 0 tensor(0.5717)
1655 0 tensor(0.5395)
1656 0 tensor(0.5341)
1657 0 tensor(0.5455)
1658 0 tensor(0.5812)
1659 0 tensor(0.5421)
1660 0 tensor(0.5329)
1661 0 tensor(0.5270)
1662 0 tensor(0.5274)
1663 0 tensor(0.5450)
1664 0 tensor(0.5784)
1665 0 tensor(0.5396)
1666 0 tensor(0.5286)
1667 0 tensor(0.5288)
1668 0 tensor(0.5597)
1669 0 tensor(0.5371)
1670 0 tensor(0.5357)
1671 0 tensor(0.5456)
1672 0 tensor(0.5814)
1673 0 tensor(0.5422)
1674 0 tensor(0.5337)
1675 0 tensor(0.5268)
1676 0 tensor(0.5238)
1677 0 tensor(0.5309)
1678 0 tensor(0.5715)
1679 0 tensor(0.5381)
1680 0 tensor(0.5275)
1681 0 tensor(0.5285)
1682 0 tensor(0.5593)
1683 0 tensor(0.5366)
1684 0 tensor(0.5357)
1685 0 tensor(0.5444)
1686 0 tensor(0.5816)
1687 0 tensor(0.5418)
1688 0 tensor(0.5333)
1689 0 tensor(0.5261)
1690 0 tensor(0.5224)
1691 0 tensor(0.5266)
1692 0 tensor(0.5631)
1693 0 tensor(0.5356)
1694 0 tensor(0.5284)
1695 0 tensor(0.5388)
1696 0 tensor(0.5807)
1697 0 tensor(0.5405)
1698 0 tensor(0.5312)
1699 0 tensor(0.5245)
1700 0 tensor(0.5237)
1701 0 tensor(0.5384)
1702 0 tensor(0.5801)
1703 0 tensor(0.5389)
1704 0 tensor(0.5284)
1705 0 tensor(0.5238)
1706 0 tensor(0.5280)
1707 0 tensor(0.5541)
1708 0 tensor(0.5721)
1709 0 tensor(0.5360)
1710 0 tensor(0.5310)
1711 0 tensor(0.5447)
1712 0 tensor(0.5823)
1713 0 tensor(0.5388)
1714 0 tensor(0.5282)
1715 0 tensor(0.5226)
1716 0 tensor(0.5250)
1717 0 tensor(0.5491)
1718 0 tensor(0.5744)
1719 0 tensor(0.5346)
1720 0 tensor(0.5254)
1721 0 tensor(0.5385)
1722 0 tensor(0.5807)
1723 0 tensor(0.5374)
1724 0 tensor(0.5263)
1725 0 tensor(0.5214)
1726 0 tensor(0.5248)
1727 0 tensor(0.5531)
1728 0 tensor(0.5680)
1729 0 tensor(0.5355)
1730 0 tensor(0.5380)
1731 0 tensor(0.5500)
1732 0 tensor(0.5803)
1733 0 tensor(0.5354)
1734 0 tensor(0.5235)
1735 0 tensor(0.5215)
1736 0 tensor(0.5484)
1737 0 tensor(0.5343)
1738 0 tensor(0.5450)
1739 0 tensor(0.5450)
1740 0 tensor(0.5826)
1741 0 tensor(0.5389)
1742 0 tensor(0.5296)
1743 0 tensor(0.5215)
1744 0 tensor(0.5176)
1745 0 tensor(0.5204)
1746 0 tensor(0.5535)
1747 0 tensor(0.5317)
1748 0 tensor(0.5346)
1749 0 tensor(0.5425)
1750 0 tensor(0.5825)
1751 0 tensor(0.5385)
1752 0 tensor(0.5290)

1753 0 tensor(0.5211)
1754 0 tensor(0.5178)
1755 0 tensor(0.5236)
1756 0 tensor(0.5649)
1757 0 tensor(0.5317)
1758 0 tensor(0.5220)
1759 0 tensor(0.5293)
1760 0 tensor(0.5745)
1761 0 tensor(0.5346)
1762 0 tensor(0.5234)
1763 0 tensor(0.5203)
1764 0 tensor(0.5265)
1765 0 tensor(0.5534)
1766 0 tensor(0.5705)
1767 0 tensor(0.5320)
1768 0 tensor(0.5276)
1769 0 tensor(0.5411)
1770 0 tensor(0.5822)
1771 0 tensor(0.5355)
1772 0 tensor(0.5241)
1773 0 tensor(0.5181)
1774 0 tensor(0.5195)
1775 0 tensor(0.5437)
1776 0 tensor(0.5742)
1777 0 tensor(0.5303)
1778 0 tensor(0.5200)
1779 0 tensor(0.5328)
1780 0 tensor(0.5786)
1781 0 tensor(0.5331)
1782 0 tensor(0.5212)
1783 0 tensor(0.5169)
1784 0 tensor(0.5250)
1785 0 tensor(0.5518)
1786 0 tensor(0.5697)
1787 0 tensor(0.5303)
1788 0 tensor(0.5278)
1789 0 tensor(0.5419)
1790 0 tensor(0.5813)
1791 0 tensor(0.5333)
1792 0 tensor(0.5213)
1793 0 tensor(0.5163)
1794 0 tensor(0.5205)
1795 0 tensor(0.5504)
1796 0 tensor(0.5652)
1797 0 tensor(0.5311)
1798 0 tensor(0.5383)
1799 0 tensor(0.5446)
1800 0 tensor(0.5818)
1801 0 tensor(0.5324)
1802 0 tensor(0.5200)
1803 0 tensor(0.5143)
1804 0 tensor(0.5182)
1805 0 tensor(0.5487)
1806 0 tensor(0.5635)
1807 0 tensor(0.5317)
1808 0 tensor(0.5602)
1809 0 tensor(0.5251)
1810 0 tensor(0.5167)
1811 0 tensor(0.5301)
1812 0 tensor(0.5765)
1813 0 tensor(0.5303)
1814 0 tensor(0.5183)
1815 0 tensor(0.5153)
1816 0 tensor(0.5355)
1817 0 tensor(0.5387)
1818 0 tensor(0.5827)
1819 0 tensor(0.5347)
1820 0 tensor(0.5238)
1821 0 tensor(0.5156)
1822 0 tensor(0.5130)
1823 0 tensor(0.5204)
1824 0 tensor(0.5653)
1825 0 tensor(0.5273)
1826 0 tensor(0.5166)
1827 0 tensor(0.5221)
1828 0 tensor(0.5672)
1829 0 tensor(0.5281)
1830 0 tensor(0.5169)
1831 0 tensor(0.5189)
1832 0 tensor(0.5578)
1833 0 tensor(0.5260)
1834 0 tensor(0.5195)
1835 0 tensor(0.5300)
1836 0 tensor(0.5789)
1837 0 tensor(0.5323)
1838 0 tensor(0.5209)
1839 0 tensor(0.5146)
1840 0 tensor(0.5158)
1841 0 tensor(0.5348)
1842 0 tensor(0.5791)
1843 0 tensor(0.5303)
1844 0 tensor(0.5181)
1845 0 tensor(0.5138)
1846 0 tensor(0.5208)
1847 0 tensor(0.5485)
1848 0 tensor(0.5702)
1849 0 tensor(0.5261)
1850 0 tensor(0.5204)
1851 0 tensor(0.5364)
1852 0 tensor(0.5802)
1853 0 tensor(0.5296)
1854 0 tensor(0.5170)
1855 0 tensor(0.5122)
1856 0 tensor(0.5210)
1857 0 tensor(0.5467)
1858 0 tensor(0.5717)
1859 0 tensor(0.5253)
1860 0 tensor(0.5164)
1861 0 tensor(0.5317)
1862 0 tensor(0.5785)
1863 0 tensor(0.5286)
1864 0 tensor(0.5161)
1865 0 tensor(0.5117)
1866 0 tensor(0.5235)
1867 0 tensor(0.5448)
1868 0 tensor(0.5759)
1869 0 tensor(0.5263)
1870 0 tensor(0.5138)
1871 0 tensor(0.5192)
1872 0 tensor(0.5658)
1873 0 tensor(0.5248)
1874 0 tensor(0.5133)
1875 0 tensor(0.5169)
1876 0 tensor(0.5594)
1877 0 tensor(0.5233)
1878 0 tensor(0.5145)
1879 0 tensor(0.5240)
1880 0 tensor(0.5745)
1881 0 tensor(0.5281)
1882 0 tensor(0.5164)
1883 0 tensor(0.5121)
1884 0 tensor(0.5150)
1885 0 tensor(0.5434)
1886 0 tensor(0.5701)
1887 0 tensor(0.5234)
1888 0 tensor(0.5160)
1889 0 tensor(0.5327)
1890 0 tensor(0.5787)
1891 0 tensor(0.5271)
1892 0 tensor(0.5144)
1893 0 tensor(0.5102)
1894 0 tensor(0.5283)
1895 0 tensor(0.5355)
1896 0 tensor(0.5836)
1897 0 tensor(0.5310)
1898 0 tensor(0.5190)
1899 0 tensor(0.5106)
1900 0 tensor(0.5085)
1901 0 tensor(0.5179)
1902 0 tensor(0.5664)
1903 0 tensor(0.5239)
1904 0 tensor(0.5121)
1905 0 tensor(0.5149)
1906 0 tensor(0.5567)
1907 0 tensor(0.5216)
1908 0 tensor(0.5140)
1909 0 tensor(0.5249)
1910 0 tensor(0.5770)
1911 0 tensor(0.5281)
1912 0 tensor(0.5163)
1913 0 tensor(0.5105)
1914 0 tensor(0.5121)
1915 0 tensor(0.5343)
1916 0 tensor(0.5773)
1917 0 tensor(0.5256)
1918 0 tensor(0.5126)
1919 0 tensor(0.5117)
1920 0 tensor(0.5466)
1921 0 tensor(0.5204)
1922 0 tensor(0.5241)
1923 0 tensor(0.5317)
1924 0 tensor(0.5826)
1925 0 tensor(0.5301)
1926 0 tensor(0.5183)
1927 0 tensor(0.5099)
1928 0 tensor(0.5072)
1929 0 tensor(0.5135)
1930 0 tensor(0.5584)
1931 0 tensor(0.5208)
1932 0 tensor(0.5115)
1933 0 tensor(0.5210)
1934 0 tensor(0.5733)
1935 0 tensor(0.5258)
1936 0 tensor(0.5139)
1937 0 tensor(0.5096)
1938 0 tensor(0.5128)
1939 0 tensor(0.5412)
1940 0 tensor(0.5716)
1941 0 tensor(0.5215)
1942 0 tensor(0.5106)
1943 0 tensor(0.5246)
1944 0 tensor(0.5763)
1945 0 tensor(0.5251)
1946 0 tensor(0.5124)
1947 0 tensor(0.5074)
1948 0 tensor(0.5153)
1949 0 tensor(0.5418)
1950 0 tensor(0.5726)
1951 0 tensor(0.5211)
1952 0 tensor(0.5092)
1953 0 tensor(0.5216)
1954 0 tensor(0.5739)
1955 0 tensor(0.5239)
1956 0 tensor(0.5112)
1957 0 tensor(0.5073)
1958 0 tensor(0.5242)
1959 0 tensor(0.5341)
1960 0 tensor(0.5839)
1961 0 tensor(0.5282)
1962 0 tensor(0.5158)
1963 0 tensor(0.5074)
1964 0 tensor(0.5057)
1965 0 tensor(0.5176)
1966 0 tensor(0.5698)
1967 0 tensor(0.5225)
1968 0 tensor(0.5099)
1969 0 tensor(0.5088)
1970 0 tensor(0.5396)
1971 0 tensor(0.5188)
1972 0 tensor(0.5259)
1973 0 tensor(0.5367)
1974 0 tensor(0.5842)
1975 0 tensor(0.5276)
1976 0 tensor(0.5152)
1977 0 tensor(0.5068)
1978 0 tensor(0.5056)
1979 0 tensor(0.5186)
1980 0 tensor(0.5718)
1981 0 tensor(0.5227)
1982 0 tensor(0.5102)
1983 0 tensor(0.5072)
1984 0 tensor(0.5238)
1985 0 tensor(0.5334)
1986 0 tensor(0.5846)
1987 0 tensor(0.5279)
1988 0 tensor(0.5154)
1989 0 tensor(0.5064)
1990 0 tensor(0.5040)
1991 0 tensor(0.5119)
1992 0 tensor(0.5604)
1993 0 tensor(0.5185)
1994 0 tensor(0.5071)
1995 0 tensor(0.5129)
1996 0 tensor(0.5608)
1997 0 tensor(0.5187)
1998 0 tensor(0.5072)
1999 0 tensor(0.5121)
2000 0 tensor(0.5586)
2001 0 tensor(0.5180)
2002 0 tensor(0.5073)
2003 0 tensor(0.5139)
2004 0 tensor(0.5635)
2005 0 tensor(0.5195)
2006 0 tensor(0.5072)
2007 0 tensor(0.5094)
2008 0 tensor(0.5506)
2009 0 tensor(0.5161)
2010 0 tensor(0.5115)
2011 0 tensor(0.5217)
2012 0 tensor(0.5771)
2013 0 tensor(0.5246)
2014 0 tensor(0.5128)
2015 0 tensor(0.5060)
2016 0 tensor(0.5073)
2017 0 tensor(0.5242)
2018 0 tensor(0.5794)
2019 0 tensor(0.5246)
2020 0 tensor(0.5122)
2021 0 tensor(0.5052)
2022 0 tensor(0.5056)
2023 0 tensor(0.5255)
2024 0 tensor(0.5773)
2025 0 tensor(0.5226)
2026 0 tensor(0.5094)
2027 0 tensor(0.5044)
2028 0 tensor(0.5116)
2029 0 tensor(0.5380)
2030 0 tensor(0.5740)
2031 0 tensor(0.5187)
2032 0 tensor(0.5048)
2033 0 tensor(0.5117)
2034 0 tensor(0.5625)
2035 0 tensor(0.5172)
2036 0 tensor(0.5045)
2037 0 tensor(0.5070)
2038 0 tensor(0.5474)
2039 0 tensor(0.5139)
2040 0 tensor(0.5126)
2041 0 tensor(0.5233)
2042 0 tensor(0.5802)
2043 0 tensor(0.5247)
2044 0 tensor(0.5127)
2045 0 tensor(0.5045)
2046 0 tensor(0.5036)
2047 0 tensor(0.5148)
2048 0 tensor(0.5703)
2049 0 tensor(0.5203)
2050 0 tensor(0.5076)
2051 0 tensor(0.5044)
2052 0 tensor(0.5136)
2053 0 tensor(0.5373)
2054 0 tensor(0.5770)
2055 0 tensor(0.5197)
2056 0 tensor(0.5053)
2057 0 tensor(0.5062)
2058 0 tensor(0.5456)
2059 0 tensor(0.5123)
2060 0 tensor(0.5118)
2061 0 tensor(0.5236)
2062 0 tensor(0.5810)
2063 0 tensor(0.5242)
2064 0 tensor(0.5121)
2065 0 tensor(0.5035)
2066 0 tensor(0.5021)
2067 0 tensor(0.5119)
2068 0 tensor(0.5658)
2069 0 tensor(0.5177)
2070 0 tensor(0.5047)
2071 0 tensor(0.5043)
2072 0 tensor(0.5349)
2073 0 tensor(0.5129)
2074 0 tensor(0.5191)
2075 0 tensor(0.5331)
2076 0 tensor(0.5836)
2077 0 tensor(0.5237)
2078 0 tensor(0.5109)
2079 0 tensor(0.5026)
2080 0 tensor(0.5018)
2081 0 tensor(0.5176)
2082 0 tensor(0.5737)
2083 0 tensor(0.5199)
2084 0 tensor(0.5067)
2085 0 tensor(0.5020)
2086 0 tensor(0.5076)
2087 0 tensor(0.5351)
2088 0 tensor(0.5724)
2089 0 tensor(0.5158)
2090 0 tensor(0.5019)
2091 0 tensor(0.5090)
2092 0 tensor(0.5603)
2093 0 tensor(0.5141)
2094 0 tensor(0.5014)
2095 0 tensor(0.5035)
2096 0 tensor(0.5420)
2097 0 tensor(0.5107)
2098 0 tensor(0.5129)
2099 0 tensor(0.5216)
2100 0 tensor(0.5801)
2101 0 tensor(0.5227)
2102 0 tensor(0.5107)
2103 0 tensor(0.5022)
2104 0 tensor(0.5013)
2105 0 tensor(0.5116)
2106 0 tensor(0.5672)
2107 0 tensor(0.5170)
2108 0 tensor(0.5038)
2109 0 tensor(0.5020)
2110 0 tensor(0.5209)
2111 0 tensor(0.5238)
2112 0 tensor(0.5828)
2113 0 tensor(0.5237)
2114 0 tensor(0.5115)
2115 0 tensor(0.5018)
2116 0 tensor(0.4986)
2117 0 tensor(0.5017)
2118 0 tensor(0.5389)
2119 0 tensor(0.5100)
2120 0 tensor(0.5145)
2121 0 tensor(0.5209)
2122 0 tensor(0.5799)
2123 0 tensor(0.5222)
2124 0 tensor(0.5103)
2125 0 tensor(0.5016)
2126 0 tensor(0.5004)
2127 0 tensor(0.5095)
2128 0 tensor(0.5636)
2129 0 tensor(0.5150)
2130 0 tensor(0.5018)
2131 0 tensor(0.5018)
2132 0 tensor(0.5330)
2133 0 tensor(0.5097)
2134 0 tensor(0.5151)
2135 0 tensor(0.5295)
2136 0 tensor(0.5839)
2137 0 tensor(0.5224)
2138 0 tensor(0.5096)
2139 0 tensor(0.5005)
2140 0 tensor(0.4993)

2141 0 tensor(0.5107)
2142 0 tensor(0.5679)
2143 0 tensor(0.5163)
2144 0 tensor(0.5027)
2145 0 tensor(0.5001)
2146 0 tensor(0.5139)
2147 0 tensor(0.5289)
2148 0 tensor(0.5832)
2149 0 tensor(0.5216)
2150 0 tensor(0.5084)
2151 0 tensor(0.4999)
2152 0 tensor(0.4988)
2153 0 tensor(0.5153)
2154 0 tensor(0.5730)
2155 0 tensor(0.5174)
2156 0 tensor(0.5037)
2157 0 tensor(0.4990)
2158 0 tensor(0.5048)
2159 0 tensor(0.5313)
2160 0 tensor(0.5736)
2161 0 tensor(0.5145)
2162 0 tensor(0.4994)
2163 0 tensor(0.5019)
2164 0 tensor(0.5426)
2165 0 tensor(0.5068)
2166 0 tensor(0.5052)
2167 0 tensor(0.5179)
2168 0 tensor(0.5790)
2169 0 tensor(0.5202)
2170 0 tensor(0.5077)
2171 0 tensor(0.4996)
2172 0 tensor(0.4996)
2173 0 tensor(0.5130)
2174 0 tensor(0.5732)
2175 0 tensor(0.5175)
2176 0 tensor(0.5043)
2177 0 tensor(0.4991)
2178 0 tensor(0.4995)
2179 0 tensor(0.5299)
2180 0 tensor(0.5685)
2181 0 tensor(0.5110)
2182 0 tensor(0.4982)
2183 0 tensor(0.5085)
2184 0 tensor(0.5648)
2185 0 tensor(0.5131)
2186 0 tensor(0.4991)
2187 0 tensor(0.4971)
2188 0 tensor(0.5223)
2189 0 tensor(0.5085)
2190 0 tensor(0.5492)
2191 0 tensor(0.5076)
2192 0 tensor(0.5017)
2193 0 tensor(0.5113)
2194 0 tensor(0.5696)
2195 0 tensor(0.5153)
2196 0 tensor(0.5017)
2197 0 tensor(0.4982)
2198 0 tensor(0.5021)
2199 0 tensor(0.5302)
2200 0 tensor(0.5719)
2201 0 tensor(0.5120)
2202 0 tensor(0.4972)
2203 0 tensor(0.5008)
2204 0 tensor(0.5439)
2205 0 tensor(0.5051)
2206 0 tensor(0.5011)
2207 0 tensor(0.5132)
2208 0 tensor(0.5747)
2209 0 tensor(0.5170)
2210 0 tensor(0.5038)
2211 0 tensor(0.4978)
2212 0 tensor(0.4974)
2213 0 tensor(0.5249)
2214 0 tensor(0.5708)
2215 0 tensor(0.5113)
2216 0 tensor(0.4965)
2217 0 tensor(0.4992)
2218 0 tensor(0.5395)
2219 0 tensor(0.5039)
2220 0 tensor(0.5035)
2221 0 tensor(0.5167)
2222 0 tensor(0.5794)
2223 0 tensor(0.5186)
2224 0 tensor(0.5057)
2225 0 tensor(0.4976)
2226 0 tensor(0.4974)
2227 0 tensor(0.5117)
2228 0 tensor(0.5733)
2229 0 tensor(0.5157)
2230 0 tensor(0.5020)
2231 0 tensor(0.4967)
2232 0 tensor(0.4967)
2233 0 tensor(0.5300)
2234 0 tensor(0.5641)
2235 0 tensor(0.5072)
2236 0 tensor(0.4980)
2237 0 tensor(0.5147)
2238 0 tensor(0.5732)
2239 0 tensor(0.5144)
2240 0 tensor(0.4995)
2241 0 tensor(0.4944)
2242 0 tensor(0.5043)
2243 0 tensor(0.5250)
2244 0 tensor(0.5775)
2245 0 tensor(0.5148)
2246 0 tensor(0.4995)
2247 0 tensor(0.4948)
2248 0 tensor(0.5107)
2249 0 tensor(0.5203)
2250 0 tensor(0.5819)
2251 0 tensor(0.5188)
2252 0 tensor(0.5057)
2253 0 tensor(0.4964)
2254 0 tensor(0.4950)
2255 0 tensor(0.5063)
2256 0 tensor(0.5648)
2257 0 tensor(0.5111)
2258 0 tensor(0.4969)
2259 0 tensor(0.4943)
2260 0 tensor(0.5045)
2261 0 tensor(0.5247)
2262 0 tensor(0.5787)
2263 0 tensor(0.5155)
2264 0 tensor(0.5005)
2265 0 tensor(0.4945)
2266 0 tensor(0.4970)
2267 0 tensor(0.5315)
2268 0 tensor(0.5617)
2269 0 tensor(0.5051)
2270 0 tensor(0.4968)
2271 0 tensor(0.5196)
2272 0 tensor(0.5709)
2273 0 tensor(0.5103)
2274 0 tensor(0.4949)
2275 0 tensor(0.4932)
2276 0 tensor(0.5220)
2277 0 tensor(0.5018)
2278 0 tensor(0.5220)
2279 0 tensor(0.5122)
2280 0 tensor(0.5713)
2281 0 tensor(0.5134)
2282 0 tensor(0.4991)
2283 0 tensor(0.4942)
2284 0 tensor(0.4943)
2285 0 tensor(0.5301)
2286 0 tensor(0.5591)
2287 0 tensor(0.5037)
2288 0 tensor(0.4955)
2289 0 tensor(0.5277)
2290 0 tensor(0.5617)
2291 0 tensor(0.5036)
2292 0 tensor(0.4935)
2293 0 tensor(0.5196)
2294 0 tensor(0.5648)
2295 0 tensor(0.5053)
2296 0 tensor(0.4919)
2297 0 tensor(0.5022)
2298 0 tensor(0.5557)
2299 0 tensor(0.5047)
2300 0 tensor(0.4922)
2301 0 tensor(0.4908)
2302 0 tensor(0.5168)
2303 0 tensor(0.5044)
2304 0 tensor(0.5546)
2305 0 tensor(0.5052)
2306 0 tensor(0.4932)
2307 0 tensor(0.4916)
2308 0 tensor(0.5020)
2309 0 tensor(0.5244)
2310 0 tensor(0.5768)
2311 0 tensor(0.5120)
2312 0 tensor(0.4958)
2313 0 tensor(0.4924)
2314 0 tensor(0.5152)
2315 0 tensor(0.5091)
2316 0 tensor(0.5677)
2317 0 tensor(0.5104)
2318 0 tensor(0.4955)
2319 0 tensor(0.4920)
2320 0 tensor(0.4950)
2321 0 tensor(0.5293)
2322 0 tensor(0.5620)
2323 0 tensor(0.5032)
2324 0 tensor(0.4949)
2325 0 tensor(0.5129)
2326 0 tensor(0.5727)
2327 0 tensor(0.5113)
2328 0 tensor(0.4955)
2329 0 tensor(0.4906)
2330 0 tensor(0.5020)
2331 0 tensor(0.5214)
2332 0 tensor(0.5775)
2333 0 tensor(0.5126)
2334 0 tensor(0.4967)
2335 0 tensor(0.4913)
2336 0 tensor(0.4997)
2337 0 tensor(0.5232)
2338 0 tensor(0.5738)
2339 0 tensor(0.5095)
2340 0 tensor(0.4934)
2341 0 tensor(0.4901)
2342 0 tensor(0.5143)
2343 0 tensor(0.5046)
2344 0 tensor(0.5581)
2345 0 tensor(0.5054)
2346 0 tensor(0.4921)
2347 0 tensor(0.4893)
2348 0 tensor(0.4867)
2349 0 tensor(0.5109)
2350 0 tensor(0.5583)
2351 0 tensor(0.5017)
2352 0 tensor(0.4909)
2353 0 tensor(0.5009)
2354 0 tensor(0.5586)
2355 0 tensor(0.5048)
2356 0 tensor(0.4910)
2357 0 tensor(0.4874)
2358 0 tensor(0.4868)
2359 0 tensor(0.5213)
2360 0 tensor(0.5543)
2361 0 tensor(0.4990)
2362 0 tensor(0.4885)
2363 0 tensor(0.5295)
2364 0 tensor(0.5466)
2365 0 tensor(0.5096)
2366 0 tensor(0.5674)
2367 0 tensor(0.5088)
2368 0 tensor(0.4924)
2369 0 tensor(0.4870)
2370 0 tensor(0.4997)
2371 0 tensor(0.5188)
2372 0 tensor(0.5783)
2373 0 tensor(0.5120)
2374 0 tensor(0.4955)
2375 0 tensor(0.4900)
2376 0 tensor(0.4981)
2377 0 tensor(0.5240)
2378 0 tensor(0.5716)
2379 0 tensor(0.5061)
2380 0 tensor(0.4903)
2381 0 tensor(0.4887)
2382 0 tensor(0.5168)
2383 0 tensor(0.5006)
2384 0 tensor(0.5502)
2385 0 tensor(0.5009)
2386 0 tensor(0.4901)
2387 0 tensor(0.4876)
2388 0 tensor(0.4888)
2389 0 tensor(0.5277)
2390 0 tensor(0.5528)
2391 0 tensor(0.4983)
2392 0 tensor(0.5016)
2393 0 tensor(0.5291)
2394 0 tensor(0.5628)
2395 0 tensor(0.5001)
2396 0 tensor(0.4895)
2397 0 tensor(0.5143)
2398 0 tensor(0.5642)
2399 0 tensor(0.5022)
2400 0 tensor(0.4879)
2401 0 tensor(0.4941)
2402 0 tensor(0.5437)
2403 0 tensor(0.4972)
2404 0 tensor(0.4894)
2405 0 tensor(0.4928)
2406 0 tensor(0.5360)
2407 0 tensor(0.4962)
2408 0 tensor(0.4963)
2409 0 tensor(0.5118)
2410 0 tensor(0.5791)
2411 0 tensor(0.5132)
2412 0 tensor(0.4977)
2413 0 tensor(0.4910)
2414 0 tensor(0.4885)
2415 0 tensor(0.5228)
2416 0 tensor(0.5595)
2417 0 tensor(0.4990)
2418 0 tensor(0.4904)
2419 0 tensor(0.5123)
2420 0 tensor(0.5693)
2421 0 tensor(0.5058)
2422 0 tensor(0.4896)
2423 0 tensor(0.4851)
2424 0 tensor(0.4983)
2425 0 tensor(0.5169)
2426 0 tensor(0.5788)
2427 0 tensor(0.5115)
2428 0 tensor(0.4949)
2429 0 tensor(0.4887)
2430 0 tensor(0.4902)
2431 0 tensor(0.5295)
2432 0 tensor(0.5533)
2433 0 tensor(0.4962)
2434 0 tensor(0.4885)
2435 0 tensor(0.5391)
2436 0 tensor(0.5290)
2437 0 tensor(0.5387)
2438 0 tensor(0.5534)
2439 0 tensor(0.4985)
2440 0 tensor(0.5316)
2441 0 tensor(0.4923)
2442 0 tensor(0.4844)
2443 0 tensor(0.5119)
2444 0 tensor(0.5554)
2445 0 tensor(0.4967)
2446 0 tensor(0.4865)
2447 0 tensor(0.5110)
2448 0 tensor(0.5596)
2449 0 tensor(0.4986)
2450 0 tensor(0.4861)
2451 0 tensor(0.4965)
2452 0 tensor(0.5511)
2453 0 tensor(0.4979)
2454 0 tensor(0.4867)
2455 0 tensor(0.4854)
2456 0 tensor(0.5104)
2457 0 tensor(0.5074)
2458 0 tensor(0.5730)
2459 0 tensor(0.5091)
2460 0 tensor(0.4924)
2461 0 tensor(0.4874)
2462 0 tensor(0.4850)
2463 0 tensor(0.5274)
2464 0 tensor(0.5442)
2465 0 tensor(0.5052)
2466 0 tensor(0.5635)
2467 0 tensor(0.5045)
2468 0 tensor(0.4885)
2469 0 tensor(0.4829)
2470 0 tensor(0.4823)
2471 0 tensor(0.4879)
2472 0 tensor(0.5173)
2473 0 tensor(0.5637)
2474 0 tensor(0.4991)
2475 0 tensor(0.4858)
2476 0 tensor(0.4930)
2477 0 tensor(0.5459)
2478 0 tensor(0.4956)
2479 0 tensor(0.4863)
2480 0 tensor(0.4850)
2481 0 tensor(0.5135)
2482 0 tensor(0.5002)
2483 0 tensor(0.5566)
2484 0 tensor(0.5004)
2485 0 tensor(0.4875)
2486 0 tensor(0.4847)
2487 0 tensor(0.4852)
2488 0 tensor(0.5132)
2489 0 tensor(0.5049)
2490 0 tensor(0.5688)
2491 0 tensor(0.5061)
2492 0 tensor(0.4894)
2493 0 tensor(0.4851)
2494 0 tensor(0.4816)
2495 0 tensor(0.4901)
2496 0 tensor(0.5137)
2497 0 tensor(0.5745)
2498 0 tensor(0.5064)
2499 0 tensor(0.4886)
2500 0 tensor(0.4836)
2501 0 tensor(0.4811)
2502 0 tensor(0.4835)
2503 0 tensor(0.5134)
2504 0 tensor(0.5585)
2505 0 tensor(0.4960)
2506 0 tensor(0.4859)
2507 0 tensor(0.5043)
2508 0 tensor(0.5652)
2509 0 tensor(0.5020)
2510 0 tensor(0.4861)
2511 0 tensor(0.4813)
2512 0 tensor(0.4930)
2513 0 tensor(0.5163)
2514 0 tensor(0.5774)
2515 0 tensor(0.5073)
2516 0 tensor(0.4889)
2517 0 tensor(0.4836)
2518 0 tensor(0.4815)
2519 0 tensor(0.5153)
2520 0 tensor(0.5535)
2521 0 tensor(0.4931)
2522 0 tensor(0.4808)
2523 0 tensor(0.4905)
2524 0 tensor(0.5423)
2525 0 tensor(0.4929)
2526 0 tensor(0.4851)
2527 0 tensor(0.4889)
2528 0 tensor(0.5354)
2529 0 tensor(0.4918)
2530 0 tensor(0.4904)
2531 0 tensor(0.5084)
2532 0 tensor(0.5787)
2533 0 tensor(0.5098)
2534 0 tensor(0.4917)
2535 0 tensor(0.4861)
2536 0 tensor(0.4863)
2537 0 tensor(0.5290)
2538 0 tensor(0.5490)
2539 0 tensor(0.4949)
2540 0 tensor(0.5346)
2541 0 tensor(0.4910)
2542 0 tensor(0.4866)
2543 0 tensor(0.4980)
2544 0 tensor(0.5632)
2545 0 tensor(0.5017)
2546 0 tensor(0.4864)
2547 0 tensor(0.4831)
2548 0 tensor(0.4871)
2549 0 tensor(0.5312)
2550 0 tensor(0.4909)
2551 0 tensor(0.4882)
2552 0 tensor(0.5154)
2553 0 tensor(0.5719)
2554 0 tensor(0.5025)
2555 0 tensor(0.4855)
2556 0 tensor(0.4802)
2557 0 tensor(0.4815)
2558 0 tensor(0.5237)
2559 0 tensor(0.5458)
2560 0 tensor(0.4972)
2561 0 tensor(0.5444)
2562 0 tensor(0.4926)
2563 0 tensor(0.4829)
2564 0 tensor(0.4891)
2565 0 tensor(0.5410)
2566 0 tensor(0.4915)
2567 0 tensor(0.4847)

2568 0 tensor(0.4856)
2569 0 tensor(0.5245)
2570 0 tensor(0.4904)
2571 0 tensor(0.4903)
2572 0 tensor(0.5264)
2573 0 tensor(0.5611)
2574 0 tensor(0.4945)
2575 0 tensor(0.4856)
2576 0 tensor(0.5004)
2577 0 tensor(0.5675)
2578 0 tensor(0.5031)
2579 0 tensor(0.4861)
2580 0 tensor(0.4819)
2581 0 tensor(0.4874)
2582 0 tensor(0.5362)
2583 0 tensor(0.4901)
2584 0 tensor(0.4874)
2585 0 tensor(0.4996)
2586 0 tensor(0.5677)
2587 0 tensor(0.5031)
2588 0 tensor(0.4863)
2589 0 tensor(0.4828)
2590 0 tensor(0.4813)
2591 0 tensor(0.5067)
2592 0 tensor(0.5056)
2593 0 tensor(0.5760)
2594 0 tensor(0.5082)
2595 0 tensor(0.4902)
2596 0 tensor(0.4849)
2597 0 tensor(0.4818)
2598 0 tensor(0.5263)
2599 0 tensor(0.5458)
2600 0 tensor(0.4955)
2601 0 tensor(0.5403)
2602 0 tensor(0.4904)
2603 0 tensor(0.4826)
2604 0 tensor(0.4889)
2605 0 tensor(0.5419)
2606 0 tensor(0.4909)
2607 0 tensor(0.4832)
2608 0 tensor(0.4807)
2609 0 tensor(0.5071)
2610 0 tensor(0.5014)
2611 0 tensor(0.5655)
2612 0 tensor(0.5016)
2613 0 tensor(0.4857)
2614 0 tensor(0.4828)
2615 0 tensor(0.4805)
2616 0 tensor(0.5067)
2617 0 tensor(0.5020)
2618 0 tensor(0.5670)
2619 0 tensor(0.5023)
2620 0 tensor(0.4859)
2621 0 tensor(0.4826)
2622 0 tensor(0.4791)
2623 0 tensor(0.4891)
2624 0 tensor(0.5162)
2625 0 tensor(0.5763)
2626 0 tensor(0.5039)
2627 0 tensor(0.4853)
2628 0 tensor(0.4807)
2629 0 tensor(0.4843)
2630 0 tensor(0.5265)
2631 0 tensor(0.4877)
2632 0 tensor(0.4845)
2633 0 tensor(0.5291)
2634 0 tensor(0.5483)
2635 0 tensor(0.4909)
2636 0 tensor(0.5298)
2637 0 tensor(0.4878)
2638 0 tensor(0.4824)
2639 0 tensor(0.5078)
2640 0 tensor(0.5658)
2641 0 tensor(0.4980)
2642 0 tensor(0.4824)
2643 0 tensor(0.4796)
2644 0 tensor(0.5002)
2645 0 tensor(0.5138)
2646 0 tensor(0.5815)
2647 0 tensor(0.5087)
2648 0 tensor(0.4895)
2649 0 tensor(0.4831)
2650 0 tensor(0.4836)
2651 0 tensor(0.5291)
2652 0 tensor(0.5461)
2653 0 tensor(0.4922)
2654 0 tensor(0.5345)
2655 0 tensor(0.4878)
2656 0 tensor(0.4821)
2657 0 tensor(0.4959)
2658 0 tensor(0.5610)
2659 0 tensor(0.4985)
2660 0 tensor(0.4840)
2661 0 tensor(0.4798)
2662 0 tensor(0.4998)
2663 0 tensor(0.5598)
2664 0 tensor(0.4957)
2665 0 tensor(0.4822)
2666 0 tensor(0.4778)
2667 0 tensor(0.4938)
2668 0 tensor(0.5151)
2669 0 tensor(0.5806)
2670 0 tensor(0.5071)
2671 0 tensor(0.4877)
2672 0 tensor(0.4818)
2673 0 tensor(0.4776)
2674 0 tensor(0.5113)
2675 0 tensor(0.5542)
2676 0 tensor(0.4895)
2677 0 tensor(0.4788)
2678 0 tensor(0.5109)
2679 0 tensor(0.5540)
2680 0 tensor(0.4895)
2681 0 tensor(0.4773)
2682 0 tensor(0.5000)
2683 0 tensor(0.5516)
2684 0 tensor(0.4903)
2685 0 tensor(0.4790)
2686 0 tensor(0.4918)
2687 0 tensor(0.5486)
2688 0 tensor(0.4909)
2689 0 tensor(0.4803)
2690 0 tensor(0.4797)
2691 0 tensor(0.5070)
2692 0 tensor(0.5049)
2693 0 tensor(0.5783)
2694 0 tensor(0.5080)
2695 0 tensor(0.4889)
2696 0 tensor(0.4825)
2697 0 tensor(0.4789)
2698 0 tensor(0.5274)
2699 0 tensor(0.5383)
2700 0 tensor(0.5028)
2701 0 tensor(0.5710)
2702 0 tensor(0.5054)
2703 0 tensor(0.4860)
2704 0 tensor(0.4790)
2705 0 tensor(0.4810)
2706 0 tensor(0.5154)
2707 0 tensor(0.4908)
2708 0 tensor(0.5420)
2709 0 tensor(0.4895)
2710 0 tensor(0.4815)
2711 0 tensor(0.4760)
2712 0 tensor(0.4756)
2713 0 tensor(0.4758)
2714 0 tensor(0.4943)
2715 0 tensor(0.5519)
2716 0 tensor(0.4907)
2717 0 tensor(0.4796)
2718 0 tensor(0.4793)
2719 0 tensor(0.5084)
2720 0 tensor(0.5022)
2721 0 tensor(0.5751)
2722 0 tensor(0.5057)
2723 0 tensor(0.4863)
2724 0 tensor(0.4805)
2725 0 tensor(0.4758)
2726 0 tensor(0.4882)
2727 0 tensor(0.5128)
2728 0 tensor(0.5799)
2729 0 tensor(0.5052)
2730 0 tensor(0.4854)
2731 0 tensor(0.4799)
2732 0 tensor(0.4769)
2733 0 tensor(0.4941)
2734 0 tensor(0.5166)
2735 0 tensor(0.5799)
2736 0 tensor(0.5046)
2737 0 tensor(0.4849)
2738 0 tensor(0.4796)
2739 0 tensor(0.4782)
2740 0 tensor(0.5015)
2741 0 tensor(0.5102)
2742 0 tensor(0.5825)
2743 0 tensor(0.5087)
2744 0 tensor(0.4895)
2745 0 tensor(0.4826)
2746 0 tensor(0.4803)
2747 0 tensor(0.5270)
2748 0 tensor(0.5450)
2749 0 tensor(0.4878)
2750 0 tensor(0.5276)
2751 0 tensor(0.4844)
2752 0 tensor(0.4760)
2753 0 tensor(0.5087)
2754 0 tensor(0.5528)
2755 0 tensor(0.4874)
2756 0 tensor(0.4758)
2757 0 tensor(0.4934)
2758 0 tensor(0.5486)
2759 0 tensor(0.4890)
2760 0 tensor(0.4782)
2761 0 tensor(0.4782)
2762 0 tensor(0.5050)
2763 0 tensor(0.5052)
2764 0 tensor(0.5789)
2765 0 tensor(0.5073)
2766 0 tensor(0.4875)
2767 0 tensor(0.4809)
2768 0 tensor(0.4762)
2769 0 tensor(0.5198)
2770 0 tensor(0.5453)
2771 0 tensor(0.4849)
2772 0 tensor(0.5202)
2773 0 tensor(0.4831)
2774 0 tensor(0.4776)
2775 0 tensor(0.5329)
2776 0 tensor(0.5250)
2777 0 tensor(0.5195)
2778 0 tensor(0.5616)
2779 0 tensor(0.4907)
2780 0 tensor(0.4761)
2781 0 tensor(0.4787)
2782 0 tensor(0.5284)
2783 0 tensor(0.5343)
2784 0 tensor(0.5042)
2785 0 tensor(0.5693)
2786 0 tensor(0.5015)
2787 0 tensor(0.4823)
2788 0 tensor(0.4748)
2789 0 tensor(0.4876)
2790 0 tensor(0.5129)
2791 0 tensor(0.5752)
2792 0 tensor(0.5009)
2793 0 tensor(0.4829)
2794 0 tensor(0.4790)
2795 0 tensor(0.4878)
2796 0 tensor(0.5474)
2797 0 tensor(0.4892)
2798 0 tensor(0.4807)
2799 0 tensor(0.4744)
2800 0 tensor(0.4970)
2801 0 tensor(0.5529)
2802 0 tensor(0.4886)
2803 0 tensor(0.4779)
2804 0 tensor(0.4762)
2805 0 tensor(0.4944)
2806 0 tensor(0.5175)
2807 0 tensor(0.5730)
2808 0 tensor(0.4982)
2809 0 tensor(0.4814)
2810 0 tensor(0.4739)
2811 0 tensor(0.4808)
2812 0 tensor(0.5256)
2813 0 tensor(0.4820)
2814 0 tensor(0.4755)
2815 0 tensor(0.5236)
2816 0 tensor(0.5357)
2817 0 tensor(0.4981)
2818 0 tensor(0.5651)
2819 0 tensor(0.5007)
2820 0 tensor(0.4821)
2821 0 tensor(0.4742)
2822 0 tensor(0.4866)
2823 0 tensor(0.5425)
2824 0 tensor(0.4858)
2825 0 tensor(0.4777)
2826 0 tensor(0.4784)
2827 0 tensor(0.5125)
2828 0 tensor(0.4914)
2829 0 tensor(0.5480)
2830 0 tensor(0.4893)
2831 0 tensor(0.4806)
2832 0 tensor(0.4754)
2833 0 tensor(0.5211)
2834 0 tensor(0.5406)
2835 0 tensor(0.4878)
2836 0 tensor(0.5353)
2837 0 tensor(0.4839)
2838 0 tensor(0.4763)
2839 0 tensor(0.4945)
2840 0 tensor(0.5543)
2841 0 tensor(0.4908)
2842 0 tensor(0.4792)
2843 0 tensor(0.4753)
2844 0 tensor(0.5256)
2845 0 tensor(0.5323)
2846 0 tensor(0.5022)
2847 0 tensor(0.5669)
2848 0 tensor(0.5003)
2849 0 tensor(0.4813)
2850 0 tensor(0.4738)
2851 0 tensor(0.4896)
2852 0 tensor(0.5126)
2853 0 tensor(0.5779)
2854 0 tensor(0.5027)
2855 0 tensor(0.4831)
2856 0 tensor(0.4788)
2857 0 tensor(0.4764)
2858 0 tensor(0.5082)
2859 0 tensor(0.4899)
2860 0 tensor(0.5472)
2861 0 tensor(0.4906)
2862 0 tensor(0.4834)
2863 0 tensor(0.4805)
2864 0 tensor(0.5048)
2865 0 tensor(0.5691)
2866 0 tensor(0.4973)
2867 0 tensor(0.4819)
2868 0 tensor(0.4774)
2869 0 tensor(0.4990)
2870 0 tensor(0.5613)
2871 0 tensor(0.4944)
2872 0 tensor(0.4809)
2873 0 tensor(0.4735)
2874 0 tensor(0.5014)
2875 0 tensor(0.5524)
2876 0 tensor(0.4866)
2877 0 tensor(0.4759)
2878 0 tensor(0.4747)
2879 0 tensor(0.4899)
2880 0 tensor(0.5192)
2881 0 tensor(0.5673)
2882 0 tensor(0.4935)
2883 0 tensor(0.4790)
2884 0 tensor(0.4725)
2885 0 tensor(0.4733)
2886 0 tensor(0.5063)
2887 0 tensor(0.5506)
2888 0 tensor(0.4835)
2889 0 tensor(0.4732)
2890 0 tensor(0.4872)
2891 0 tensor(0.5131)
2892 0 tensor(0.5746)
2893 0 tensor(0.4992)
2894 0 tensor(0.4816)
2895 0 tensor(0.4767)
2896 0 tensor(0.4975)
2897 0 tensor(0.5607)
2898 0 tensor(0.4933)
2899 0 tensor(0.4805)
2900 0 tensor(0.4746)
2901 0 tensor(0.5237)
2902 0 tensor(0.5343)
2903 0 tensor(0.4934)
2904 0 tensor(0.5583)
2905 0 tensor(0.4973)
2906 0 tensor(0.4806)
2907 0 tensor(0.4720)
2908 0 tensor(0.4724)
2909 0 tensor(0.4849)
2910 0 tensor(0.5106)
2911 0 tensor(0.5739)
2912 0 tensor(0.4991)
2913 0 tensor(0.4817)
2914 0 tensor(0.4779)
2915 0 tensor(0.4911)
2916 0 tensor(0.5577)
2917 0 tensor(0.4938)
2918 0 tensor(0.4821)
2919 0 tensor(0.4771)
2920 0 tensor(0.5137)
2921 0 tensor(0.5554)
2922 0 tensor(0.4847)
2923 0 tensor(0.4750)
2924 0 tensor(0.4834)
2925 0 tensor(0.5384)
2926 0 tensor(0.4830)
2927 0 tensor(0.4761)
2928 0 tensor(0.4776)
2929 0 tensor(0.5149)
2930 0 tensor(0.4842)
2931 0 tensor(0.5349)
2932 0 tensor(0.4831)
2933 0 tensor(0.4776)
2934 0 tensor(0.4724)
2935 0 tensor(0.4896)
2936 0 tensor(0.5136)
2937 0 tensor(0.5784)
2938 0 tensor(0.5016)
2939 0 tensor(0.4822)
2940 0 tensor(0.4789)
2941 0 tensor(0.4760)
2942 0 tensor(0.4859)
2943 0 tensor(0.5186)
2944 0 tensor(0.5663)
2945 0 tensor(0.4914)
2946 0 tensor(0.4792)
2947 0 tensor(0.4740)
2948 0 tensor(0.5252)
2949 0 tensor(0.5307)
2950 0 tensor(0.4970)
2951 0 tensor(0.5625)
2952 0 tensor(0.4984)
2953 0 tensor(0.4801)
2954 0 tensor(0.4714)
2955 0 tensor(0.4743)
2956 0 tensor(0.5204)
2957 0 tensor(0.5392)
2958 0 tensor(0.4820)
2959 0 tensor(0.5204)
2960 0 tensor(0.4782)
2961 0 tensor(0.4839)
2962 0 tensor(0.5286)
2963 0 tensor(0.5441)
2964 0 tensor(0.4777)
2965 0 tensor(0.4984)
2966 0 tensor(0.5063)
2967 0 tensor(0.5761)
2968 0 tensor(0.5029)
2969 0 tensor(0.4821)
2970 0 tensor(0.4775)
2971 0 tensor(0.4743)
2972 0 tensor(0.5029)
2973 0 tensor(0.4958)
2974 0 tensor(0.5585)
2975 0 tensor(0.4937)
2976 0 tensor(0.4830)
2977 0 tensor(0.4796)
2978 0 tensor(0.4995)
2979 0 tensor(0.5678)
2980 0 tensor(0.4977)
2981 0 tensor(0.4820)
2982 0 tensor(0.4799)
2983 0 tensor(0.4852)
2984 0 tensor(0.5361)
2985 0 tensor(0.4815)
2986 0 tensor(0.4771)
2987 0 tensor(0.4722)
2988 0 tensor(0.4851)
2989 0 tensor(0.5103)
2990 0 tensor(0.5739)
2991 0 tensor(0.4992)
2992 0 tensor(0.4816)
2993 0 tensor(0.4796)
2994 0 tensor(0.4814)
2995 0 tensor(0.5300)
2996 0 tensor(0.4806)
2997 0 tensor(0.4778)
2998 0 tensor(0.4743)
2999 0 tensor(0.4730)
3000 0 tensor(0.4899)
3001 0 tensor(0.5163)
3002 0 tensor(0.5709)
3003 0 tensor(0.4957)

3004 0 tensor(0.4807)
3005 0 tensor(0.4743)
3006 0 tensor(0.5099)
3007 0 tensor(0.5528)
3008 0 tensor(0.4829)
3009 0 tensor(0.4734)
3010 0 tensor(0.4756)
3011 0 tensor(0.5094)
3012 0 tensor(0.4891)
3013 0 tensor(0.5470)
3014 0 tensor(0.4878)
3015 0 tensor(0.4803)
3016 0 tensor(0.4850)
3017 0 tensor(0.5233)
3018 0 tensor(0.5557)
3019 0 tensor(0.4830)
3020 0 tensor(0.4743)
3021 0 tensor(0.4766)
3022 0 tensor(0.5156)
3023 0 tensor(0.4803)
3024 0 tensor(0.5252)
3025 0 tensor(0.4799)
3026 0 tensor(0.4766)
3027 0 tensor(0.4830)
3028 0 tensor(0.5371)
3029 0 tensor(0.4808)
3030 0 tensor(0.4758)
3031 0 tensor(0.4734)
3032 0 tensor(0.4999)
3033 0 tensor(0.5024)
3034 0 tensor(0.5752)
3035 0 tensor(0.5022)
3036 0 tensor(0.4820)
3037 0 tensor(0.4776)
3038 0 tensor(0.4745)
3039 0 tensor(0.4726)
3040 0 tensor(0.4925)
3041 0 tensor(0.5140)
3042 0 tensor(0.5749)
3043 0 tensor(0.4988)
3044 0 tensor(0.4811)
3045 0 tensor(0.4792)
3046 0 tensor(0.4827)
3047 0 tensor(0.5328)
3048 0 tensor(0.4799)
3049 0 tensor(0.4766)
3050 0 tensor(0.4722)
3051 0 tensor(0.4742)
3052 0 tensor(0.5018)
3053 0 tensor(0.5030)
3054 0 tensor(0.5753)
3055 0 tensor(0.5024)
3056 0 tensor(0.4816)
3057 0 tensor(0.4771)
3058 0 tensor(0.4735)
3059 0 tensor(0.4734)
3060 0 tensor(0.4964)
3061 0 tensor(0.5106)
3062 0 tensor(0.5757)
3063 0 tensor(0.5004)
3064 0 tensor(0.4809)
3065 0 tensor(0.4783)
3066 0 tensor(0.4767)
3067 0 tensor(0.5061)
3068 0 tensor(0.4894)
3069 0 tensor(0.5462)
3070 0 tensor(0.4872)
3071 0 tensor(0.4821)
3072 0 tensor(0.4839)
3073 0 tensor(0.5137)
3074 0 tensor(0.5689)
3075 0 tensor(0.4948)
3076 0 tensor(0.4804)
3077 0 tensor(0.4741)
3078 0 tensor(0.5074)
3079 0 tensor(0.5556)
3080 0 tensor(0.4856)
3081 0 tensor(0.4766)
3082 0 tensor(0.4937)
3083 0 tensor(0.5093)
3084 0 tensor(0.5749)
3085 0 tensor(0.5014)
3086 0 tensor(0.4811)
3087 0 tensor(0.4772)
3088 0 tensor(0.4735)
3089 0 tensor(0.4701)
3090 0 tensor(0.4824)
3091 0 tensor(0.5047)
3092 0 tensor(0.5733)
3093 0 tensor(0.4999)
3094 0 tensor(0.4811)
3095 0 tensor(0.4789)
3096 0 tensor(0.4787)
3097 0 tensor(0.5166)
3098 0 tensor(0.4786)
3099 0 tensor(0.4763)
3100 0 tensor(0.5142)
3101 0 tensor(0.5544)
3102 0 tensor(0.4825)
3103 0 tensor(0.4737)
3104 0 tensor(0.4697)
3105 0 tensor(0.4895)
3106 0 tensor(0.5479)
3107 0 tensor(0.4853)
3108 0 tensor(0.4784)
3109 0 tensor(0.5072)
3110 0 tensor(0.4864)
3111 0 tensor(0.5397)
3112 0 tensor(0.4827)
3113 0 tensor(0.4782)
3114 0 tensor(0.4787)
3115 0 tensor(0.5195)
3116 0 tensor(0.5519)
3117 0 tensor(0.4802)
3118 0 tensor(0.4719)
3119 0 tensor(0.4770)
3120 0 tensor(0.5223)
3121 0 tensor(0.4756)
3122 0 tensor(0.4692)
3123 0 tensor(0.4790)
3124 0 tensor(0.5067)
3125 0 tensor(0.5657)
3126 0 tensor(0.4938)
3127 0 tensor(0.4793)
3128 0 tensor(0.4745)
3129 0 tensor(0.5196)
3130 0 tensor(0.5430)
3131 0 tensor(0.4735)
3132 0 tensor(0.4711)
3133 0 tensor(0.4859)
3134 0 tensor(0.5239)
3135 0 tensor(0.5534)
3136 0 tensor(0.4797)
3137 0 tensor(0.4705)
3138 0 tensor(0.4728)
3139 0 tensor(0.5254)
3140 0 tensor(0.5260)
3141 0 tensor(0.4947)
3142 0 tensor(0.5583)
3143 0 tensor(0.4939)
3144 0 tensor(0.4777)
3145 0 tensor(0.4755)
3146 0 tensor(0.5300)
3147 0 tensor(0.5221)
3148 0 tensor(0.5003)
3149 0 tensor(0.5581)
3150 0 tensor(0.4907)
3151 0 tensor(0.4782)
3152 0 tensor(0.5070)
3153 0 tensor(0.4880)
3154 0 tensor(0.5442)
3155 0 tensor(0.4843)
3156 0 tensor(0.4798)
3157 0 tensor(0.4921)
3158 0 tensor(0.5144)
3159 0 tensor(0.5678)
3160 0 tensor(0.4942)
3161 0 tensor(0.4803)
3162 0 tensor(0.4748)
3163 0 tensor(0.5068)
3164 0 tensor(0.5553)
3165 0 tensor(0.4851)
3166 0 tensor(0.4782)
3167 0 tensor(0.5105)
3168 0 tensor(0.4791)
3169 0 tensor(0.5145)
3170 0 tensor(0.4769)
3171 0 tensor(0.4766)
3172 0 tensor(0.5201)
3173 0 tensor(0.5432)
3174 0 tensor(0.4742)
3175 0 tensor(0.4793)
3176 0 tensor(0.5311)
3177 0 tensor(0.4780)
3178 0 tensor(0.4704)
3179 0 tensor(0.4753)
3180 0 tensor(0.5156)
3181 0 tensor(0.4763)
3182 0 tensor(0.5096)
3183 0 tensor(0.4796)
3184 0 tensor(0.5183)
3185 0 tensor(0.4765)
3186 0 tensor(0.4701)
3187 0 tensor(0.5092)
3188 0 tensor(0.5437)
3189 0 tensor(0.4750)
3190 0 tensor(0.4827)
3191 0 tensor(0.5404)
3192 0 tensor(0.4828)
3193 0 tensor(0.4768)
3194 0 tensor(0.5048)
3195 0 tensor(0.4881)
3196 0 tensor(0.5431)
3197 0 tensor(0.4844)
3198 0 tensor(0.4804)
3199 0 tensor(0.4900)
3200 0 tensor(0.5131)
3201 0 tensor(0.5673)
3202 0 tensor(0.4951)
3203 0 tensor(0.4803)
3204 0 tensor(0.4742)
3205 0 tensor(0.4978)
3206 0 tensor(0.5573)
3207 0 tensor(0.4917)
3208 0 tensor(0.4794)
3209 0 tensor(0.4771)
3210 0 tensor(0.5148)
3211 0 tensor(0.5510)
3212 0 tensor(0.4808)
3213 0 tensor(0.4730)
3214 0 tensor(0.4802)
3215 0 tensor(0.5154)
3216 0 tensor(0.5551)
3217 0 tensor(0.4841)
3218 0 tensor(0.4779)
3219 0 tensor(0.5162)
3220 0 tensor(0.4763)
3221 0 tensor(0.4699)
3222 0 tensor(0.5084)
3223 0 tensor(0.5430)
3224 0 tensor(0.4752)
3225 0 tensor(0.4822)
3226 0 tensor(0.5390)
3227 0 tensor(0.4824)
3228 0 tensor(0.4768)
3229 0 tensor(0.5029)
3230 0 tensor(0.4896)
3231 0 tensor(0.5466)
3232 0 tensor(0.4876)
3233 0 tensor(0.4816)
3234 0 tensor(0.4864)
3235 0 tensor(0.5123)
3236 0 tensor(0.5645)
3237 0 tensor(0.4941)
3238 0 tensor(0.4799)
3239 0 tensor(0.4737)
3240 0 tensor(0.5024)
3241 0 tensor(0.5541)
3242 0 tensor(0.4876)
3243 0 tensor(0.4789)
3244 0 tensor(0.4992)
3245 0 tensor(0.4951)
3246 0 tensor(0.5600)
3247 0 tensor(0.4977)
3248 0 tensor(0.4807)
3249 0 tensor(0.4794)
3250 0 tensor(0.4832)
3251 0 tensor(0.5346)
3252 0 tensor(0.4813)
3253 0 tensor(0.4790)
3254 0 tensor(0.4787)
3255 0 tensor(0.5027)
3256 0 tensor(0.5619)
3257 0 tensor(0.4949)
3258 0 tensor(0.4803)
3259 0 tensor(0.4748)
3260 0 tensor(0.4890)
3261 0 tensor(0.5515)
3262 0 tensor(0.4925)
3263 0 tensor(0.4805)
3264 0 tensor(0.4763)
3265 0 tensor(0.4987)
3266 0 tensor(0.5585)
3267 0 tensor(0.4946)
3268 0 tensor(0.4797)
3269 0 tensor(0.4730)
3270 0 tensor(0.4985)
3271 0 tensor(0.5533)
3272 0 tensor(0.4899)
3273 0 tensor(0.4785)
3274 0 tensor(0.4786)
3275 0 tensor(0.5162)
3276 0 tensor(0.5496)
3277 0 tensor(0.4810)
3278 0 tensor(0.4742)
3279 0 tensor(0.4961)
3280 0 tensor(0.4957)
3281 0 tensor(0.5592)
3282 0 tensor(0.4977)
3283 0 tensor(0.4805)
3284 0 tensor(0.4794)
3285 0 tensor(0.4826)
3286 0 tensor(0.5343)
3287 0 tensor(0.4819)
3288 0 tensor(0.4802)
3289 0 tensor(0.4809)
3290 0 tensor(0.4995)
3291 0 tensor(0.5640)
3292 0 tensor(0.4979)
3293 0 tensor(0.4805)
3294 0 tensor(0.4797)
3295 0 tensor(0.4823)
3296 0 tensor(0.5328)
3297 0 tensor(0.4811)
3298 0 tensor(0.4794)
3299 0 tensor(0.4789)
3300 0 tensor(0.4940)
3301 0 tensor(0.5586)
3302 0 tensor(0.4961)
3303 0 tensor(0.4809)
3304 0 tensor(0.4801)
3305 0 tensor(0.4854)
3306 0 tensor(0.5367)
3307 0 tensor(0.4827)
3308 0 tensor(0.4809)
3309 0 tensor(0.4826)
3310 0 tensor(0.5023)
3311 0 tensor(0.5653)
3312 0 tensor(0.4985)
3313 0 tensor(0.4801)
3314 0 tensor(0.4786)
3315 0 tensor(0.4783)
3316 0 tensor(0.5022)
3317 0 tensor(0.4855)
3318 0 tensor(0.5349)
3319 0 tensor(0.4808)
3320 0 tensor(0.4784)
3321 0 tensor(0.4785)
3322 0 tensor(0.5046)
3323 0 tensor(0.5587)
3324 0 tensor(0.4934)
3325 0 tensor(0.4792)
3326 0 tensor(0.4728)
3327 0 tensor(0.4995)
3328 0 tensor(0.5519)
3329 0 tensor(0.4890)
3330 0 tensor(0.4781)
3331 0 tensor(0.4810)
3332 0 tensor(0.5129)
3333 0 tensor(0.5548)
3334 0 tensor(0.4881)
3335 0 tensor(0.4779)
3336 0 tensor(0.4880)
3337 0 tensor(0.5056)
3338 0 tensor(0.5646)
3339 0 tensor(0.4990)
3340 0 tensor(0.4796)
3341 0 tensor(0.4773)
3342 0 tensor(0.4749)
3343 0 tensor(0.4835)
3344 0 tensor(0.5036)
3345 0 tensor(0.5643)
3346 0 tensor(0.4983)
3347 0 tensor(0.4799)
3348 0 tensor(0.4785)
3349 0 tensor(0.4787)
3350 0 tensor(0.5127)
3351 0 tensor(0.4755)
3352 0 tensor(0.4715)
3353 0 tensor(0.5065)
3354 0 tensor(0.5466)
3355 0 tensor(0.4798)
3356 0 tensor(0.4736)
3357 0 tensor(0.4914)
3358 0 tensor(0.5011)
3359 0 tensor(0.5655)
3360 0 tensor(0.5006)
3361 0 tensor(0.4798)
3362 0 tensor(0.4764)
3363 0 tensor(0.4738)
3364 0 tensor(0.4693)
3365 0 tensor(0.5050)
3366 0 tensor(0.5430)
3367 0 tensor(0.4769)
3368 0 tensor(0.4707)
3369 0 tensor(0.4953)
3370 0 tensor(0.4933)
3371 0 tensor(0.5521)
3372 0 tensor(0.4937)
3373 0 tensor(0.4804)
3374 0 tensor(0.4750)
3375 0 tensor(0.4866)
3376 0 tensor(0.5463)
3377 0 tensor(0.4890)
3378 0 tensor(0.4807)
3379 0 tensor(0.4813)
3380 0 tensor(0.5022)
3381 0 tensor(0.5618)

3382 0 tensor(0.4973)
3383 0 tensor(0.4796)
3384 0 tensor(0.4777)
3385 0 tensor(0.4772)
3386 0 tensor(0.5163)
3387 0 tensor(0.4757)
3388 0 tensor(0.4699)
3389 0 tensor(0.4875)
3390 0 tensor(0.5455)
3391 0 tensor(0.4861)
3392 0 tensor(0.4797)
3393 0 tensor(0.4938)
3394 0 tensor(0.4997)
3395 0 tensor(0.5635)
3396 0 tensor(0.5000)
3397 0 tensor(0.4795)
3398 0 tensor(0.4768)
3399 0 tensor(0.4746)
3400 0 tensor(0.4729)
3401 0 tensor(0.5090)
3402 0 tensor(0.5463)
3403 0 tensor(0.4790)
3404 0 tensor(0.4728)
3405 0 tensor(0.4849)
3406 0 tensor(0.5035)
3407 0 tensor(0.5641)
3408 0 tensor(0.4993)
3409 0 tensor(0.4792)
3410 0 tensor(0.4772)
3411 0 tensor(0.4755)
3412 0 tensor(0.4886)
3413 0 tensor(0.5046)
3414 0 tensor(0.5657)
3415 0 tensor(0.4994)
3416 0 tensor(0.4795)
3417 0 tensor(0.4776)
3418 0 tensor(0.4765)
3419 0 tensor(0.4848)
3420 0 tensor(0.5039)
3421 0 tensor(0.5640)
3422 0 tensor(0.4985)
3423 0 tensor(0.4795)
3424 0 tensor(0.4785)
3425 0 tensor(0.4789)
3426 0 tensor(0.5091)
3427 0 tensor(0.4752)
3428 0 tensor(0.4762)
3429 0 tensor(0.5049)
3430 0 tensor(0.5526)
3431 0 tensor(0.4879)
3432 0 tensor(0.4783)
3433 0 tensor(0.4864)
3434 0 tensor(0.5049)
3435 0 tensor(0.5624)
3436 0 tensor(0.4985)
3437 0 tensor(0.4790)
3438 0 tensor(0.4771)
3439 0 tensor(0.4751)
3440 0 tensor(0.4906)
3441 0 tensor(0.5013)
3442 0 tensor(0.5638)
3443 0 tensor(0.4999)
3444 0 tensor(0.4795)
3445 0 tensor(0.4769)
3446 0 tensor(0.4752)
3447 0 tensor(0.4742)
3448 0 tensor(0.5020)
3449 0 tensor(0.5512)
3450 0 tensor(0.4871)
3451 0 tensor(0.4786)
3452 0 tensor(0.4897)
3453 0 tensor(0.5024)
3454 0 tensor(0.5630)
3455 0 tensor(0.5000)
3456 0 tensor(0.4791)
3457 0 tensor(0.4764)
3458 0 tensor(0.4740)
3459 0 tensor(0.4716)
3460 0 tensor(0.5091)
3461 0 tensor(0.5429)
3462 0 tensor(0.4767)
3463 0 tensor(0.4700)
3464 0 tensor(0.4745)
3465 0 tensor(0.5055)
3466 0 tensor(0.5485)
3467 0 tensor(0.4832)
3468 0 tensor(0.4795)
3469 0 tensor(0.5271)
3470 0 tensor(0.4768)
3471 0 tensor(0.4733)
3472 0 tensor(0.4671)
3473 0 tensor(0.4664)
3474 0 tensor(0.4788)
3475 0 tensor(0.5309)
3476 0 tensor(0.4753)
3477 0 tensor(0.4701)
3478 0 tensor(0.4718)
3479 0 tensor(0.4994)
3480 0 tensor(0.4919)
3481 0 tensor(0.5539)
3482 0 tensor(0.4956)
3483 0 tensor(0.4792)
3484 0 tensor(0.4733)
3485 0 tensor(0.4814)
3486 0 tensor(0.5343)
3487 0 tensor(0.4772)
3488 0 tensor(0.4731)
3489 0 tensor(0.4684)
3490 0 tensor(0.5072)
3491 0 tensor(0.5388)
3492 0 tensor(0.4726)
3493 0 tensor(0.4821)
3494 0 tensor(0.5388)
3495 0 tensor(0.4820)
3496 0 tensor(0.4782)
3497 0 tensor(0.5171)
3498 0 tensor(0.4740)
3499 0 tensor(0.4668)
3500 0 tensor(0.4702)
3501 0 tensor(0.4917)
3502 0 tensor(0.5049)
3503 0 tensor(0.5628)
3504 0 tensor(0.4982)
3505 0 tensor(0.4785)
3506 0 tensor(0.4753)
3507 0 tensor(0.4719)
3508 0 tensor(0.4872)
3509 0 tensor(0.5043)
3510 0 tensor(0.5650)
3511 0 tensor(0.4995)
3512 0 tensor(0.4790)
3513 0 tensor(0.4778)
3514 0 tensor(0.4780)
3515 0 tensor(0.5045)
3516 0 tensor(0.4796)
3517 0 tensor(0.5297)
3518 0 tensor(0.4771)
3519 0 tensor(0.4747)
3520 0 tensor(0.4705)
3521 0 tensor(0.4924)
3522 0 tensor(0.5500)
3523 0 tensor(0.4886)
3524 0 tensor(0.4790)
3525 0 tensor(0.4815)
3526 0 tensor(0.5037)
3527 0 tensor(0.5590)
3528 0 tensor(0.4960)
3529 0 tensor(0.4785)
3530 0 tensor(0.4728)
3531 0 tensor(0.4785)
3532 0 tensor(0.5232)
3533 0 tensor(0.4735)
3534 0 tensor(0.4674)
3535 0 tensor(0.4673)
3536 0 tensor(0.4832)
3537 0 tensor(0.5008)
3538 0 tensor(0.5625)
3539 0 tensor(0.4995)
3540 0 tensor(0.4785)
3541 0 tensor(0.4768)
3542 0 tensor(0.4755)
3543 0 tensor(0.4943)
3544 0 tensor(0.4967)
3545 0 tensor(0.5583)
3546 0 tensor(0.4980)
3547 0 tensor(0.4793)
3548 0 tensor(0.4791)
3549 0 tensor(0.4816)
3550 0 tensor(0.5294)
3551 0 tensor(0.4764)
3552 0 tensor(0.4744)
3553 0 tensor(0.4693)
3554 0 tensor(0.4881)
3555 0 tensor(0.5466)
3556 0 tensor(0.4869)
3557 0 tensor(0.4794)
3558 0 tensor(0.4862)
3559 0 tensor(0.5036)
3560 0 tensor(0.5620)
3561 0 tensor(0.4992)
3562 0 tensor(0.4784)
3563 0 tensor(0.4767)
3564 0 tensor(0.4752)
3565 0 tensor(0.4846)
3566 0 tensor(0.5012)
3567 0 tensor(0.5621)
3568 0 tensor(0.4997)
3569 0 tensor(0.4786)
3570 0 tensor(0.4769)
3571 0 tensor(0.4758)
3572 0 tensor(0.4798)
3573 0 tensor(0.4950)
3574 0 tensor(0.5568)
3575 0 tensor(0.4975)
3576 0 tensor(0.4789)
3577 0 tensor(0.4778)
3578 0 tensor(0.4782)
3579 0 tensor(0.5151)
3580 0 tensor(0.4739)
3581 0 tensor(0.4679)
3582 0 tensor(0.4797)
3583 0 tensor(0.5326)
3584 0 tensor(0.4758)
3585 0 tensor(0.4713)
3586 0 tensor(0.4655)
3587 0 tensor(0.4669)
3588 0 tensor(0.4831)
3589 0 tensor(0.4998)
3590 0 tensor(0.5619)
3591 0 tensor(0.5000)
3592 0 tensor(0.4781)
3593 0 tensor(0.4763)
3594 0 tensor(0.4748)
3595 0 tensor(0.4840)
3596 0 tensor(0.5017)
3597 0 tensor(0.5623)
3598 0 tensor(0.4994)
3599 0 tensor(0.4784)
3600 0 tensor(0.4774)
3601 0 tensor(0.4772)
3602 0 tensor(0.4961)
3603 0 tensor(0.4919)
3604 0 tensor(0.5490)
3605 0 tensor(0.4917)
3606 0 tensor(0.4801)
3607 0 tensor(0.4767)
3608 0 tensor(0.4794)
3609 0 tensor(0.5218)
3610 0 tensor(0.4733)
3611 0 tensor(0.4695)
3612 0 tensor(0.4751)
3613 0 tensor(0.5146)
3614 0 tensor(0.4707)
3615 0 tensor(0.4652)
3616 0 tensor(0.4744)
3617 0 tensor(0.4948)
3618 0 tensor(0.5532)
3619 0 tensor(0.4932)
3620 0 tensor(0.4771)
3621 0 tensor(0.4734)
3622 0 tensor(0.4922)
3623 0 tensor(0.5519)
3624 0 tensor(0.4932)
3625 0 tensor(0.4774)
3626 0 tensor(0.4737)
3627 0 tensor(0.4879)
3628 0 tensor(0.5487)
3629 0 tensor(0.4919)
3630 0 tensor(0.4782)
3631 0 tensor(0.4758)
3632 0 tensor(0.4844)
3633 0 tensor(0.5407)
3634 0 tensor(0.4835)
3635 0 tensor(0.4798)
3636 0 tensor(0.4924)
3637 0 tensor(0.4973)
3638 0 tensor(0.5590)
3639 0 tensor(0.5000)
3640 0 tensor(0.4781)
3641 0 tensor(0.4765)
3642 0 tensor(0.4753)
3643 0 tensor(0.4776)
3644 0 tensor(0.4920)
3645 0 tensor(0.5533)
3646 0 tensor(0.4958)
3647 0 tensor(0.4786)
3648 0 tensor(0.4747)
3649 0 tensor(0.4707)
3650 0 tensor(0.4752)
3651 0 tensor(0.4946)
3652 0 tensor(0.5531)
3653 0 tensor(0.4943)
3654 0 tensor(0.4776)
3655 0 tensor(0.4711)
3656 0 tensor(0.4860)
3657 0 tensor(0.5450)
3658 0 tensor(0.4887)
3659 0 tensor(0.4784)
3660 0 tensor(0.4775)
3661 0 tensor(0.4959)
3662 0 tensor(0.5548)
3663 0 tensor(0.4968)
3664 0 tensor(0.4778)
3665 0 tensor(0.4735)
3666 0 tensor(0.4690)
3667 0 tensor(0.4712)
3668 0 tensor(0.5034)
3669 0 tensor(0.5455)
3670 0 tensor(0.4803)
3671 0 tensor(0.4781)
3672 0 tensor(0.5259)
3673 0 tensor(0.4751)
3674 0 tensor(0.4722)
3675 0 tensor(0.4662)
3676 0 tensor(0.4655)
3677 0 tensor(0.4833)
3678 0 tensor(0.4973)
3679 0 tensor(0.5594)
3680 0 tensor(0.4999)
3681 0 tensor(0.4779)
3682 0 tensor(0.4767)
3683 0 tensor(0.4760)
3684 0 tensor(0.4889)
3685 0 tensor(0.5008)
3686 0 tensor(0.5616)
3687 0 tensor(0.5005)
3688 0 tensor(0.4779)
3689 0 tensor(0.4762)
3690 0 tensor(0.4752)
3691 0 tensor(0.4757)
3692 0 tensor(0.4915)
3693 0 tensor(0.5522)
3694 0 tensor(0.4943)
3695 0 tensor(0.4781)
3696 0 tensor(0.4720)
3697 0 tensor(0.4787)
3698 0 tensor(0.5254)
3699 0 tensor(0.4730)
3700 0 tensor(0.4696)
3701 0 tensor(0.4722)
3702 0 tensor(0.5017)
3703 0 tensor(0.4815)
3704 0 tensor(0.5266)
3705 0 tensor(0.4734)
3706 0 tensor(0.4707)
3707 0 tensor(0.4694)
3708 0 tensor(0.5018)
3709 0 tensor(0.4781)
3710 0 tensor(0.5210)
3711 0 tensor(0.4733)
3712 0 tensor(0.4717)
3713 0 tensor(0.4676)
3714 0 tensor(0.4677)
3715 0 tensor(0.4855)
3716 0 tensor(0.5032)
3717 0 tensor(0.5621)
3718 0 tensor(0.4998)
3719 0 tensor(0.4775)
3720 0 tensor(0.4757)
3721 0 tensor(0.4740)
3722 0 tensor(0.4861)
3723 0 tensor(0.5021)
3724 0 tensor(0.5624)
3725 0 tensor(0.5004)
3726 0 tensor(0.4777)
3727 0 tensor(0.4764)
3728 0 tensor(0.4756)
3729 0 tensor(0.4816)
3730 0 tensor(0.4962)
3731 0 tensor(0.5581)
3732 0 tensor(0.4988)
3733 0 tensor(0.4779)
3734 0 tensor(0.4771)
3735 0 tensor(0.4772)
3736 0 tensor(0.5024)
3737 0 tensor(0.4784)
3738 0 tensor(0.5277)
3739 0 tensor(0.4748)
3740 0 tensor(0.4728)
3741 0 tensor(0.4671)
3742 0 tensor(0.4767)
3743 0 tensor(0.5253)
3744 0 tensor(0.4721)
3745 0 tensor(0.4668)
3746 0 tensor(0.4701)
3747 0 tensor(0.4961)
3748 0 tensor(0.4929)
3749 0 tensor(0.5552)
3750 0 tensor(0.4984)
3751 0 tensor(0.4773)
3752 0 tensor(0.4740)
3753 0 tensor(0.4701)
3754 0 tensor(0.4685)
3755 0 tensor(0.5070)
3756 0 tensor(0.5394)
3757 0 tensor(0.4728)
3758 0 tensor(0.4711)
3759 0 tensor(0.5016)
3760 0 tensor(0.4799)
3761 0 tensor(0.5273)
3762 0 tensor(0.4735)
3763 0 tensor(0.4708)
3764 0 tensor(0.4661)
3765 0 tensor(0.4781)
3766 0 tensor(0.4869)
3767 0 tensor(0.5461)
3768 0 tensor(0.4871)
3769 0 tensor(0.4801)
3770 0 tensor(0.4830)
3771 0 tensor(0.5000)
3772 0 tensor(0.5602)
3773 0 tensor(0.4995)
3774 0 tensor(0.4774)
3775 0 tensor(0.4759)
3776 0 tensor(0.4747)
3777 0 tensor(0.4875)
3778 0 tensor(0.5005)
3779 0 tensor(0.5612)
3780 0 tensor(0.5009)
3781 0 tensor(0.4773)
3782 0 tensor(0.4757)
3783 0 tensor(0.4746)
3784 0 tensor(0.4743)
3785 0 tensor(0.4897)
3786 0 tensor(0.5503)
3787 0 tensor(0.4926)
3788 0 tensor(0.4776)
3789 0 tensor(0.4745)
3790 0 tensor(0.4758)
3791 0 tensor(0.5135)
3792 0 tensor(0.4706)

3793 0 tensor(0.4648)
3794 0 tensor(0.4817)
3795 0 tensor(0.5367)
3796 0 tensor(0.4767)
3797 0 tensor(0.4717)
3798 0 tensor(0.4791)
3799 0 tensor(0.4918)
3800 0 tensor(0.5539)
3801 0 tensor(0.4971)
3802 0 tensor(0.4773)
3803 0 tensor(0.4727)
3804 0 tensor(0.4679)
3805 0 tensor(0.4647)
3806 0 tensor(0.4923)
3807 0 tensor(0.5399)
3808 0 tensor(0.4756)
3809 0 tensor(0.4692)
3810 0 tensor(0.4774)
3811 0 tensor(0.4899)
3812 0 tensor(0.5522)
3813 0 tensor(0.4952)
3814 0 tensor(0.4768)
3815 0 tensor(0.4704)
3816 0 tensor(0.4820)
3817 0 tensor(0.5392)
3818 0 tensor(0.4802)
3819 0 tensor(0.4778)
3820 0 tensor(0.5018)
3821 0 tensor(0.4789)
3822 0 tensor(0.5291)
3823 0 tensor(0.4747)
3824 0 tensor(0.4721)
3825 0 tensor(0.4675)
3826 0 tensor(0.4847)
3827 0 tensor(0.5434)
3828 0 tensor(0.4839)
3829 0 tensor(0.4790)
3830 0 tensor(0.5015)
3831 0 tensor(0.4793)
3832 0 tensor(0.5273)
3833 0 tensor(0.4736)
3834 0 tensor(0.4712)
3835 0 tensor(0.4654)
3836 0 tensor(0.4668)
3837 0 tensor(0.4824)
3838 0 tensor(0.4981)
3839 0 tensor(0.5591)
3840 0 tensor(0.5002)
3841 0 tensor(0.4767)
3842 0 tensor(0.4746)
3843 0 tensor(0.4720)
3844 0 tensor(0.4726)
3845 0 tensor(0.4940)
3846 0 tensor(0.5503)
3847 0 tensor(0.4897)
3848 0 tensor(0.4769)
3849 0 tensor(0.4757)
3850 0 tensor(0.4940)
3851 0 tensor(0.5525)
3852 0 tensor(0.4945)
3853 0 tensor(0.4760)
3854 0 tensor(0.4707)
3855 0 tensor(0.4822)
3856 0 tensor(0.5390)
3857 0 tensor(0.4807)
3858 0 tensor(0.4779)
3859 0 tensor(0.5013)
3860 0 tensor(0.4781)
3861 0 tensor(0.5280)
3862 0 tensor(0.4745)
3863 0 tensor(0.4721)
3864 0 tensor(0.4669)
3865 0 tensor(0.4804)
3866 0 tensor(0.5357)
3867 0 tensor(0.4763)
3868 0 tensor(0.4726)
3869 0 tensor(0.4747)
3870 0 tensor(0.4921)
3871 0 tensor(0.5512)
3872 0 tensor(0.4936)
3873 0 tensor(0.4761)
3874 0 tensor(0.4721)
3875 0 tensor(0.4783)
3876 0 tensor(0.5258)
3877 0 tensor(0.4721)
3878 0 tensor(0.4687)
3879 0 tensor(0.4703)
3880 0 tensor(0.4966)
3881 0 tensor(0.4872)
3882 0 tensor(0.5413)
3883 0 tensor(0.4829)
3884 0 tensor(0.4791)
3885 0 tensor(0.4934)
3886 0 tensor(0.4922)
3887 0 tensor(0.5507)
3888 0 tensor(0.4947)
3889 0 tensor(0.4775)
3890 0 tensor(0.4717)
3891 0 tensor(0.4682)
3892 0 tensor(0.4981)
3893 0 tensor(0.4790)
3894 0 tensor(0.5256)
3895 0 tensor(0.4729)
3896 0 tensor(0.4714)
3897 0 tensor(0.4683)
3898 0 tensor(0.4713)
3899 0 tensor(0.4999)
3900 0 tensor(0.4823)
3901 0 tensor(0.5289)
3902 0 tensor(0.4726)
3903 0 tensor(0.4699)
3904 0 tensor(0.4655)
3905 0 tensor(0.4844)
3906 0 tensor(0.4953)
3907 0 tensor(0.5557)
3908 0 tensor(0.4985)
3909 0 tensor(0.4770)
3910 0 tensor(0.4751)
3911 0 tensor(0.4731)
3912 0 tensor(0.4811)
3913 0 tensor(0.4927)
3914 0 tensor(0.5534)
3915 0 tensor(0.4965)
3916 0 tensor(0.4774)
3917 0 tensor(0.4731)
3918 0 tensor(0.4687)
3919 0 tensor(0.4640)
3920 0 tensor(0.4865)
3921 0 tensor(0.5390)
3922 0 tensor(0.4762)
3923 0 tensor(0.4711)
3924 0 tensor(0.4868)
3925 0 tensor(0.4970)
3926 0 tensor(0.5582)
3927 0 tensor(0.5012)
3928 0 tensor(0.4763)
3929 0 tensor(0.4745)
3930 0 tensor(0.4724)
3931 0 tensor(0.4701)
3932 0 tensor(0.4946)
3933 0 tensor(0.5474)
3934 0 tensor(0.4854)
3935 0 tensor(0.4777)
3936 0 tensor(0.5023)
3937 0 tensor(0.4755)
3938 0 tensor(0.5222)
3939 0 tensor(0.4724)
3940 0 tensor(0.4711)
3941 0 tensor(0.4697)
3942 0 tensor(0.4660)
3943 0 tensor(0.4820)
3944 0 tensor(0.4930)
3945 0 tensor(0.5527)
3946 0 tensor(0.4958)
3947 0 tensor(0.4773)
3948 0 tensor(0.4719)
3949 0 tensor(0.4669)
3950 0 tensor(0.4629)
3951 0 tensor(0.4654)
3952 0 tensor(0.4795)
3953 0 tensor(0.4924)
3954 0 tensor(0.5548)
3955 0 tensor(0.4976)
3956 0 tensor(0.4761)
3957 0 tensor(0.4702)
3958 0 tensor(0.4703)
3959 0 tensor(0.5040)
3960 0 tensor(0.4737)
3961 0 tensor(0.4952)
3962 0 tensor(0.4885)
3963 0 tensor(0.5429)
3964 0 tensor(0.4834)
3965 0 tensor(0.4796)
3966 0 tensor(0.4877)
3967 0 tensor(0.4987)
3968 0 tensor(0.5588)
3969 0 tensor(0.5013)
3970 0 tensor(0.4761)
3971 0 tensor(0.4746)
3972 0 tensor(0.4728)
3973 0 tensor(0.4704)
3974 0 tensor(0.4906)
3975 0 tensor(0.5476)
3976 0 tensor(0.4882)
3977 0 tensor(0.4767)
3978 0 tensor(0.4769)
3979 0 tensor(0.4867)
3980 0 tensor(0.5461)
3981 0 tensor(0.4898)
3982 0 tensor(0.4771)
3983 0 tensor(0.4746)
3984 0 tensor(0.4776)
3985 0 tensor(0.5202)
3986 0 tensor(0.4704)
3987 0 tensor(0.4648)
3988 0 tensor(0.4666)
3989 0 tensor(0.5017)
3990 0 tensor(0.5390)
3991 0 tensor(0.4735)
3992 0 tensor(0.4665)
3993 0 tensor(0.4766)
3994 0 tensor(0.4820)
3995 0 tensor(0.5356)
3996 0 tensor(0.4757)
3997 0 tensor(0.4718)
3998 0 tensor(0.4716)
3999 0 tensor(0.4939)

In [54]:
test_loss=0
correct=0

In [56]:
inputs,labels=test[0,:,[0,1,2,3,4,5,6,7,8,9]],test[0,:,[-1]]
data,target=Variable(inputs),Variable(labels)    
output=model(data)
test_loss+=criterion(output,labels).data[0]

    

print('\nTest set:Average loss:,Accuracy:/{}({:.0f}%)\n'.format(len(test_loader.dataset),
                                                                            100.*correct/len(test_loader.dataset)))

Test set:Average loss:,Accuracy:/1(0%)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  after removing the cwd from sys.path.

In [63]:
output=output.detach().numpy()

In [65]:
result=np.where(output>0.5,1,0)

In [66]:
result

array([[1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [68]:
label_num=labels.detach().numpy()

In [70]:
label_num

array([[ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.]], dtype=float32)

In [69]:
np.nonzero(result==label_num)

(array([  0,   1,   2,   4,   6,   7,   8,   9,  10,  12,  15,  16,  17,
         18,  19,  22,  24,  25,  26,  27,  28,  29,  30,  31,  33,  35,
         36,  37,  38,  39,  41,  42,  43,  44,  45,  46,  47,  48,  49,
         51,  53,  54,  56,  57,  58,  59,  60,  61,  62,  65,  67,  68,
         69,  70,  71,  73,  74,  76,  77,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100, 101, 102, 104, 105, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 126, 129,
        131, 134, 135, 136, 137, 138, 139, 141, 142, 143, 144, 146, 147,
        148, 149, 151, 156, 157, 158, 159, 160, 162, 165, 168, 172, 173,
        178, 179, 180, 182, 183, 184, 185, 186, 187, 188, 190, 191, 196,
        197, 198, 199, 200, 202, 203, 204, 207, 208, 211, 212, 213, 214,
        215, 216, 217, 219, 221, 222], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0], dtype=int64))

In [73]:
np.size(np.nonzero(result==label_num),1)

162

In [78]:
rightness=np.size(np.nonzero(result==label_num),1)/np.size(result,0)

In [80]:
rightness

0.726457399103139